/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const UpdateEngineAdminsParams = IDL.Record({
		engine_id: IDL.Text,
		principals: IDL.Vec(IDL.Principal)
	});
	const EngineError = IDL.Variant({
		RoleAlreadyGranted: IDL.Null,
		EngineNotFound: IDL.Null,
		EngineAlreadyExists: IDL.Null,
		CannotRemoveCreator: IDL.Null,
		RoleNotAllowed: IDL.Null,
		RoleNotGranted: IDL.Null,
		Unauthorized: IDL.Null,
		NameTooLong: IDL.Null
	});
	const EngineResult = IDL.Variant({ Ok: IDL.Null, Err: EngineError });
	const UpdateGroupAdminsParams = IDL.Record({
		group_id: IDL.Text,
		principals: IDL.Vec(IDL.Principal)
	});
	const GroupError = IDL.Variant({
		GroupNotFound: IDL.Null,
		EmptyTradingAccess: IDL.Null,
		Unauthorized: IDL.Null,
		GroupAlreadyExists: IDL.Null,
		NameTooLong: IDL.Null,
		SeriesNotFound: IDL.Null
	});
	const GroupResult = IDL.Variant({ Ok: IDL.Bool, Err: GroupError });
	const Description = IDL.Record({
		html: IDL.Opt(IDL.Text),
		markdown: IDL.Opt(IDL.Text),
		plain: IDL.Text
	});
	const OracleMetadata = IDL.Record({
		name: IDL.Text,
		description: IDL.Opt(Description),
		website: IDL.Opt(IDL.Text)
	});
	const AddOracleParams = IDL.Record({
		metadata: OracleMetadata,
		authorized_principals: IDL.Vec(IDL.Principal),
		oracle_id: IDL.Text
	});
	const OracleError = IDL.Variant({
		UnauthorizedOracleManager: IDL.Null,
		OracleAlreadyExists: IDL.Null,
		OracleNotFound: IDL.Null
	});
	const OracleResult = IDL.Variant({ Ok: IDL.Null, Err: OracleError });
	const DecimalValue = IDL.Record({ decimals: IDL.Nat8, value: IDL.Nat });
	const Price = IDL.Record({
		timestamp: IDL.Opt(IDL.Nat64),
		oracle_id: IDL.Opt(IDL.Text),
		decimal: DecimalValue
	});
	const PayoffType = IDL.Variant({
		Put: IDL.Null,
		Binary: IDL.Null,
		Call: IDL.Null,
		Categorical: IDL.Null
	});
	const FiatUnit = IDL.Variant({
		Chf: IDL.Null,
		Eur: IDL.Null,
		Gbp: IDL.Null,
		Usd: IDL.Null
	});
	const ErcToken = IDL.Record({
		decimals: IDL.Nat8,
		token_address: IDL.Text,
		chain_id: IDL.Nat64
	});
	const NativeEvmAsset = IDL.Record({
		decimals: IDL.Nat8,
		chain_id: IDL.Nat64
	});
	const Asset = IDL.Variant({
		Erc20: ErcToken,
		Icrc: IDL.Principal,
		NativeEvm: NativeEvmAsset
	});
	const SocialReward = IDL.Record({
		title: IDL.Text,
		description: IDL.Opt(IDL.Text),
		icon_url: IDL.Opt(IDL.Text)
	});
	const NonMonetaryUnit = IDL.Variant({
		Points: IDL.Null,
		Social: SocialReward
	});
	const PayoutUnit = IDL.Variant({
		Fiat: FiatUnit,
		Asset: Asset,
		NonMonetary: NonMonetaryUnit
	});
	const Resolution = IDL.Record({ clause: IDL.Text });
	const Outcome = IDL.Record({
		id: IDL.Text,
		title: IDL.Text,
		description: IDL.Opt(Description),
		icon_url: IDL.Opt(IDL.Text)
	});
	const TradingAccess = IDL.Variant({
		Open: IDL.Null,
		Restricted: IDL.Record({ groups: IDL.Vec(IDL.Text) })
	});
	const BalanceDomain = IDL.Variant({
		ViciXp: IDL.Null,
		Social: IDL.Null,
		Playground: IDL.Null,
		Settlement: IDL.Null
	});
	const AddSeriesParams = IDL.Record({
		title: IDL.Text,
		strike: IDL.Opt(Price),
		payoff_type: PayoffType,
		engine_id: IDL.Opt(IDL.Text),
		payout_unit: PayoutUnit,
		expiry_ns: IDL.Nat64,
		banner_url: IDL.Opt(IDL.Text),
		start_ns: IDL.Opt(IDL.Nat64),
		underlying: IDL.Text,
		locale: IDL.Opt(IDL.Text),
		description: Description,
		resolution: Resolution,
		outcomes: IDL.Opt(IDL.Vec(Outcome)),
		icon_url: IDL.Opt(IDL.Text),
		trading_access: IDL.Vec(TradingAccess),
		price_precision: IDL.Nat8,
		balance_domain: BalanceDomain,
		oracle_source: IDL.Text
	});
	const SeriesError = IDL.Variant({
		RewardDescriptionTooLong: IDL.Null,
		SocialMaxPerUserReached: IDL.Null,
		DescriptionTooLong: IDL.Null,
		StartNotBeforeExpiry: IDL.Null,
		TitleTooLong: IDL.Null,
		RewardIconUrlTooLong: IDL.Null,
		SocialMarketRequiresNonMonetaryPayout: IDL.Null,
		ForkLimitReached: IDL.Null,
		SocialMarketMustBeRestricted: IDL.Null,
		EngineIdRequired: IDL.Null,
		Unauthorized: IDL.Null,
		ForkMustBeRestricted: IDL.Null,
		UnsupportedPayoutUnit: IDL.Null,
		InvalidLocale: IDL.Null,
		ResolutionClauseEmpty: IDL.Null,
		SocialRateLimitExceeded: IDL.Null,
		ResolutionClauseTooLong: IDL.Null,
		SeriesAlreadyExists: IDL.Null,
		SourceSeriesNotFound: IDL.Null,
		StartNotInFuture: IDL.Null,
		RewardTitleTooLong: IDL.Null,
		SeriesNotFound: IDL.Null,
		EngineRoleNotHeld: IDL.Null
	});
	const AddSeriesResult = IDL.Variant({ Ok: IDL.Text, Err: SeriesError });
	const CreateGroupParams = IDL.Record({
		name: IDL.Text,
		description: IDL.Opt(IDL.Text),
		icon_url: IDL.Opt(IDL.Text)
	});
	const CreateGroupResult = IDL.Variant({
		Ok: IDL.Text,
		Err: GroupError
	});
	const ForkSeriesParams = IDL.Record({
		source_series_id: IDL.Text,
		title: IDL.Opt(IDL.Text),
		engine_id: IDL.Opt(IDL.Text),
		locale: IDL.Opt(IDL.Text),
		description: IDL.Opt(Description),
		resolution: IDL.Opt(Resolution),
		trading_access: IDL.Vec(TradingAccess)
	});
	const EngineRole = IDL.Variant({
		OracleAdmin: IDL.Null,
		Creator: IDL.Null
	});
	const RoleGrant = IDL.Record({
		role: EngineRole,
		granted_at_ns: IDL.Nat64,
		grantee: IDL.Principal,
		granted_by: IDL.Principal
	});
	const SocialLimits = IDL.Record({
		max_per_hour: IDL.Nat64,
		max_per_user: IDL.Nat64
	});
	const Engine = IDL.Record({
		updated_by: IDL.Principal,
		creator: IDL.Principal,
		engine_id: IDL.Text,
		name: IDL.Text,
		description: IDL.Opt(IDL.Text),
		updated_at_ns: IDL.Nat64,
		created_at_ns: IDL.Nat64,
		icon_url: IDL.Opt(IDL.Text),
		admins: IDL.Vec(IDL.Principal),
		allowed_roles: IDL.Vec(EngineRole),
		role_grants: IDL.Vec(RoleGrant),
		social_limits: IDL.Opt(SocialLimits)
	});
	const Group = IDL.Record({
		updated_by: IDL.Principal,
		creator: IDL.Principal,
		members: IDL.Vec(IDL.Principal),
		name: IDL.Text,
		description: IDL.Opt(IDL.Text),
		updated_at_ns: IDL.Nat64,
		created_at_ns: IDL.Nat64,
		icon_url: IDL.Opt(IDL.Text),
		group_id: IDL.Text,
		admins: IDL.Vec(IDL.Principal)
	});
	const Oracle = IDL.Record({
		manager: IDL.Principal,
		registered_at_ns: IDL.Nat64,
		metadata: OracleMetadata,
		authorized_principals: IDL.Vec(IDL.Principal),
		oracle_id: IDL.Text
	});
	const Series = IDL.Record({
		title: IDL.Text,
		strike: IDL.Opt(Price),
		creator: IDL.Principal,
		payoff_type: PayoffType,
		engine_id: IDL.Opt(IDL.Text),
		payout_unit: PayoutUnit,
		expiry_ns: IDL.Nat64,
		banner_url: IDL.Opt(IDL.Text),
		start_ns: IDL.Opt(IDL.Nat64),
		series_id: IDL.Text,
		underlying: IDL.Text,
		locale: IDL.Opt(IDL.Text),
		description: Description,
		resolution: Resolution,
		outcomes: IDL.Opt(IDL.Vec(Outcome)),
		created_at_ns: IDL.Nat64,
		icon_url: IDL.Opt(IDL.Text),
		trading_access: IDL.Vec(TradingAccess),
		price_precision: IDL.Nat8,
		balance_domain: BalanceDomain,
		oracle_source: IDL.Text,
		forked_from: IDL.Opt(IDL.Text)
	});
	const SeriesStatus = IDL.Variant({
		Live: IDL.Null,
		Expired: IDL.Null,
		Upcoming: IDL.Null
	});
	const GrantEngineRoleParams = IDL.Record({
		engine_id: IDL.Text,
		role: EngineRole,
		grantee: IDL.Principal
	});
	const PaginationParams = IDL.Record({
		cursor: IDL.Opt(IDL.Text),
		limit: IDL.Opt(IDL.Nat64)
	});
	const SeriesPage = IDL.Record({
		next_cursor: IDL.Opt(IDL.Text),
		items: IDL.Vec(Series)
	});
	const ListSeriesParams = IDL.Record({
		due: IDL.Opt(IDL.Bool),
		strike: IDL.Opt(Price),
		creator: IDL.Opt(IDL.Principal),
		payoff_type: IDL.Opt(PayoffType),
		payout_unit: IDL.Opt(PayoutUnit),
		tradeable_now: IDL.Opt(IDL.Bool),
		pagination: IDL.Opt(PaginationParams),
		underlying: IDL.Opt(IDL.Text),
		only_unexpired: IDL.Opt(IDL.Bool),
		search_term: IDL.Opt(IDL.Text),
		balance_domain: IDL.Opt(BalanceDomain),
		oracle_source: IDL.Opt(IDL.Text)
	});
	const ManageOraclePrincipalsParams = IDL.Record({
		add_principals: IDL.Vec(IDL.Principal),
		remove_principals: IDL.Vec(IDL.Principal),
		oracle_id: IDL.Text
	});
	const RegisterEngineParams = IDL.Record({
		name: IDL.Text,
		description: IDL.Opt(IDL.Text),
		icon_url: IDL.Opt(IDL.Text),
		admins: IDL.Vec(IDL.Principal),
		allowed_roles: IDL.Vec(EngineRole)
	});
	const RegisterEngineResult = IDL.Variant({
		Ok: IDL.Text,
		Err: EngineError
	});
	const UpdateEngineParams = IDL.Record({
		engine_id: IDL.Text,
		name: IDL.Opt(IDL.Text),
		description: IDL.Opt(IDL.Opt(IDL.Text)),
		icon_url: IDL.Opt(IDL.Opt(IDL.Text))
	});
	const UpdateEngineAllowedRolesParams = IDL.Record({
		engine_id: IDL.Text,
		allowed_roles: IDL.Vec(EngineRole)
	});
	const UpdateGroupParams = IDL.Record({
		name: IDL.Opt(IDL.Text),
		description: IDL.Opt(IDL.Opt(IDL.Text)),
		icon_url: IDL.Opt(IDL.Opt(IDL.Text)),
		group_id: IDL.Text
	});
	const UpdateOracleMetadataParams = IDL.Record({
		metadata: OracleMetadata,
		oracle_id: IDL.Text
	});
	const UpdateSeriesMetadataParams = IDL.Record({
		banner_url: IDL.Opt(IDL.Opt(IDL.Text)),
		series_id: IDL.Text,
		locale: IDL.Opt(IDL.Opt(IDL.Text)),
		description: IDL.Opt(Description),
		icon_url: IDL.Opt(IDL.Opt(IDL.Text))
	});
	const UpdateSeriesResult = IDL.Variant({
		Ok: Series,
		Err: SeriesError
	});
	const UpdateTradingAccessParams = IDL.Record({
		series_id: IDL.Text,
		trading_access: IDL.Vec(TradingAccess)
	});

	return IDL.Service({
		add_engine_admins: IDL.Func([UpdateEngineAdminsParams], [EngineResult], []),
		add_group_admins: IDL.Func([UpdateGroupAdminsParams], [GroupResult], []),
		add_group_members: IDL.Func([UpdateGroupAdminsParams], [GroupResult], []),
		add_oracle: IDL.Func([AddOracleParams], [OracleResult], []),
		add_series: IDL.Func([AddSeriesParams], [AddSeriesResult], []),
		create_group: IDL.Func([CreateGroupParams], [CreateGroupResult], []),
		delete_group: IDL.Func([IDL.Text], [GroupResult], []),
		fork_series: IDL.Func([ForkSeriesParams], [AddSeriesResult], []),
		get_engine: IDL.Func([IDL.Text], [IDL.Opt(Engine)], ['query']),
		get_group: IDL.Func([IDL.Text], [IDL.Opt(Group)], ['query']),
		get_oracle: IDL.Func([IDL.Text], [IDL.Opt(Oracle)], ['query']),
		get_series: IDL.Func([IDL.Text], [IDL.Opt(Series)], ['query']),
		get_series_status: IDL.Func([IDL.Text], [IDL.Opt(SeriesStatus)], ['query']),
		get_social_limits: IDL.Func([], [SocialLimits], ['query']),
		grant_engine_role: IDL.Func([GrantEngineRoleParams], [EngineResult], []),
		is_group_member: IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], ['query']),
		is_oracle_authorized: IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], ['query']),
		is_trading_authorized: IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], ['query']),
		list_engines: IDL.Func([], [IDL.Vec(Engine)], ['query']),
		list_groups: IDL.Func([IDL.Opt(IDL.Principal)], [IDL.Vec(Group)], ['query']),
		list_series: IDL.Func([PaginationParams], [SeriesPage], ['query']),
		list_series_with: IDL.Func([ListSeriesParams], [SeriesPage], ['query']),
		manage_oracle_principals: IDL.Func([ManageOraclePrincipalsParams], [OracleResult], []),
		register_engine: IDL.Func([RegisterEngineParams], [RegisterEngineResult], []),
		remove_engine_admins: IDL.Func([UpdateEngineAdminsParams], [EngineResult], []),
		remove_group_admins: IDL.Func([UpdateGroupAdminsParams], [GroupResult], []),
		remove_group_members: IDL.Func([UpdateGroupAdminsParams], [GroupResult], []),
		revoke_engine_role: IDL.Func([GrantEngineRoleParams], [EngineResult], []),
		set_social_limits: IDL.Func([SocialLimits], [], []),
		update_engine: IDL.Func([UpdateEngineParams], [EngineResult], []),
		update_engine_allowed_roles: IDL.Func([UpdateEngineAllowedRolesParams], [EngineResult], []),
		update_group: IDL.Func([UpdateGroupParams], [GroupResult], []),
		update_oracle_metadata: IDL.Func([UpdateOracleMetadataParams], [OracleResult], []),
		update_series_metadata: IDL.Func([UpdateSeriesMetadataParams], [UpdateSeriesResult], []),
		update_trading_access: IDL.Func([UpdateTradingAccessParams], [GroupResult], [])
	});
};

export const init = ({ IDL }) => {
	return [];
};
