/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

/**
 * Outcome of a position transfer acceptance.
 */
export type AcceptPositionTransferResult =
	| {
			/**
			 * Returns `true` if the transfer was successfully accepted and processed.
			 */
			Ok: boolean;
	  }
	| {
			/**
			 * Failed to accept the position transfer.
			 */
			Err: TradeError;
	  };
/**
 * Represents a user's account state in the clearing system.
 */
export interface AccountState {
	/**
	 * The owner of the account.
	 */
	user: Principal;
	/**
	 * The total required margin reserved for current activity, scoped by domain.
	 */
	reserved_margins_usd: Array<[BalanceDomain, bigint]>;
	/**
	 * Internal realised `PnL` / debt / credits, scoped by domain.
	 */
	cash_balances_usd: Array<[BalanceDomain, bigint]>;
	/**
	 * Real deposited collateral assets and their balances, scoped by domain.
	 */
	balances: Array<[BalanceDomain, Array<[string, bigint]>]>;
}
/**
 * Errors related to account state retrieval or state.
 */
export type AccountStateError =
	| {
			/**
			 * Overflow during account state calculation.
			 */
			MathOverflow: null;
	  }
	| {
			/**
			 * An error occurred while interacting with the asset.
			 */
			Asset: AssetError;
	  }
	| {
			/**
			 * No account state exists for the specified user.
			 */
			NoAccountStateFound: null;
	  };
/**
 * Enhanced response for account state with calculated USD values.
 */
export interface AccountStateResponse {
	/**
	 * Detailed worth of each collateral asset.
	 */
	assets: Array<AssetWorth>;
	/**
	 * The raw account state.
	 */
	state: AccountState;
	/**
	 * Total equity in USD (cash balance + sum of collateral values).
	 */
	total_equity_usd: bigint;
	/**
	 * Available equity in USD (total equity - reserved margin).
	 */
	available_margin_usd: bigint;
}
/**
 * Aggregate long/short lean of a supplied set of principals on a series,
 * broken down per outcome.
 *
 * Privacy-safe by construction: it exposes only aggregate counts over the
 * supplied set, never individual identities, sides, amounts, or P&L.
 */
export interface AggregateLean {
	/**
	 * Number of distinct supplied principals holding a non-flat position
	 * anywhere on the series (a principal long on two outcomes counts once).
	 */
	total: bigint;
	/**
	 * The series this lean was computed for.
	 */
	series_id: string;
	/**
	 * Per-outcome aggregate lean, one entry per outcome on which at least one
	 * supplied principal holds a non-flat position, ordered by outcome.
	 */
	outcomes: Array<OutcomeLean>;
}
/**
 * Input parameters for the `aggregate_lean` query.
 */
export interface AggregateLeanParams {
	/**
	 * The derivative series to aggregate the lean over.
	 */
	series_id: string;
	/**
	 * The set of principals to aggregate over. The set is caller-supplied and
	 * scanned in full, so it is capped — any list longer than the cap is
	 * truncated. Duplicate principals are de-duplicated and never affect the
	 * counts. The clearing layer ascribes no meaning to the set; how it is
	 * chosen is entirely a consumer concern.
	 */
	principals: Array<Principal>;
}
/**
 * Input parameters for
 * [`aggregate_settlement_accuracy`](super::aggregate_settlement_accuracy).
 *
 * Aggregates each supplied principal's settled-position win/total counts over
 * an arbitrary half-open time window `[from_ts, to_ts)`. Unlike
 * [`ListLeaderboardParams`] — which ranks over fixed calendar windows backed
 * by the maintained `SETTLEMENT_LEADERBOARD` index — this scans the raw event
 * log so a consumer can score a cohort over a bespoke window (e.g. a league
 * "battle" running an arbitrary 7-day span that does not align to a calendar
 * week). The clearing layer ascribes no meaning to the set or the window; how
 * they are chosen is entirely a consumer concern.
 */
export interface AggregateSettlementAccuracyParams {
	/**
	 * Exclusive upper bound on a settlement's `timestamp` (ns). `None` runs
	 * through the latest settlement. The window is half-open `[from_ts,
	 * to_ts)` so two adjacent windows that share an endpoint never both count
	 * the same settlement.
	 */
	to_ts: [] | [bigint];
	/**
	 * The principals to aggregate over (e.g. a league's member set). The set
	 * is caller-controlled and scanned in full, so it is capped at 10,000 —
	 * any realistic cohort is well under this; a longer list is truncated to
	 * the first 10,000. Duplicate principals are de-duplicated and never
	 * double-count.
	 */
	members: Array<Principal>;
	/**
	 * Inclusive lower bound on a settlement's `timestamp` (ns since the Unix
	 * epoch). `None` starts from the earliest settlement.
	 */
	from_ts: [] | [bigint];
	/**
	 * Optional series allow-list. `None` counts settlements on every series;
	 * `Some(set)` counts only settlements whose `series_id` is in the set, so
	 * a consumer can scope a cohort's accuracy to a market category (e.g. a
	 * battle scoped to one tag passes that tag's series). An empty `Some(vec)`
	 * therefore matches nothing. The clearing layer ascribes no meaning to the
	 * set; how it is chosen is entirely a consumer concern.
	 */
	series_ids: [] | [Array<string>];
}
/**
 * Represents a supported asset in the ICDC ecosystem.
 */
export type Asset =
	| {
			/**
			 * An ERC-20 token on an EVM-compatible chain.
			 */
			Erc20: ErcToken;
	  }
	| {
			/**
			 * An ICRC-compliant token identified by its canister [`Principal`].
			 */
			Icrc: Principal;
	  }
	| {
			/**
			 * A native asset on an EVM-compatible chain.
			 */
			NativeEvm: NativeEvmAsset;
	  };
/**
 * Errors related to Asset interactions.
 */
export type AssetError =
	| {
			/**
			 * Failed to transfer tokens/assets.
			 */
			TransferError: string;
	  }
	| {
			/**
			 * The account has insufficient funds for the operation.
			 */
			InsufficientBalance: {
				/**
				 * The current balance of the account.
				 */
				balance: bigint;
				/**
				 * The amount required for the operation.
				 */
				required: bigint;
			};
	  }
	| {
			/**
			 * Overflow during internal balance calculations.
			 */
			MathOverflow: null;
	  }
	| {
			/**
			 * The asset identifier is invalid or incorrectly formatted.
			 */
			InvalidAssetId: string;
	  }
	| {
			/**
			 * A cross-canister or RPC call failed.
			 */
			CallError: {
				/**
				 * The name of the method that failed.
				 */
				method: string;
				/**
				 * The rejection code from the IC or error code from RPC.
				 */
				code: number;
				/**
				 * The rejection/error message.
				 */
				message: string;
			};
	  }
	| {
			/**
			 * The asset variant is incompatible with the current handler.
			 */
			InvalidAssetForHandler: null;
	  }
	| {
			/**
			 * The specified asset is not supported.
			 */
			UnsupportedAsset: null;
	  };
/**
 * Dynamic metrics and risk parameters for a collateral asset.
 */
export interface AssetMetrics {
	/**
	 * Haircut in basis points (e.g., 1000 = 10% haircut, 90% value).
	 */
	haircut_bps: number;
	/**
	 * Latest known transfer fee for the asset.
	 */
	latest_transfer_fee: [] | [bigint];
	/**
	 * Optional asset-specific insurance fund fee ratio in basis points.
	 */
	insurance_fee_ratio: [] | [number];
	/**
	 * Last time the asset metrics were updated (in nanoseconds).
	 */
	last_updated_ns: [] | [bigint];
	/**
	 * Optional asset-specific protocol fee ratio in basis points.
	 */
	protocol_fee_ratio: [] | [number];
	/**
	 * Oracle-updated price in USD (canonical accounting unit).
	 */
	price_usd: DecimalValue;
}
/**
 * Represents the worth of a specific asset in the user's account.
 */
export interface AssetWorth {
	/**
	 * The USD value of the balance (before haircut).
	 */
	pre_haircut_value_usd: bigint;
	/**
	 * The applied haircut in basis points.
	 */
	haircut_bps: number;
	/**
	 * The raw balance of the asset.
	 */
	balance: bigint;
	/**
	 * The USD value of the balance (including haircut).
	 */
	value_usd: bigint;
	/**
	 * The unique identifier of the asset.
	 */
	asset_id: string;
}
/**
 * Input parameters for the one-shot settlement-event backfill. Synthesizes
 * `EventType::Settled` events for finalized plans that resolved before the
 * per-user event emission was added to settlement.
 */
export interface BackfillSettlementEventsParams {
	/**
	 * Resume after this series id (exclusive). `None` starts from the lowest
	 * series id. Callers re-invoke with the previous response's `next_cursor`
	 * until it comes back as `None`.
	 */
	start_after: [] | [string];
}
/**
 * Outcome of one chunk of the settlement-event backfill.
 */
export interface BackfillSettlementEventsResult {
	/**
	 * Number of finalized plans visited in this chunk.
	 */
	plans_scanned: bigint;
	/**
	 * Number of `Settled` events newly written in this chunk.
	 */
	events_emitted: bigint;
	/**
	 * Number of `SettlementPosition`s skipped because their series already has
	 * at least one pre-existing `Settled` event (idempotent skip). Counted
	 * per-position to mirror the live emission contract, which writes one
	 * event per position.
	 */
	events_skipped: bigint;
	/**
	 * When `Some`, pass back as `start_after` to continue. `None` means the
	 * backfill is complete.
	 */
	next_cursor: [] | [string];
}
/**
 * Represents a distinct domain for balances and trading logic.
 */
export type BalanceDomain =
	| {
			/**
			 * VICI XP (loyalty points) — segregated from Playground test assets.
			 */
			ViciXp: null;
	  }
	| {
			/**
			 * Non-monetary social bets (e.g., betting a pizza).
			 */
			Social: null;
	  }
	| {
			/**
			 * Testnet / sandbox collateral (e.g. TESTICP, Sepolia) — not real funds.
			 */
			Playground: null;
	  }
	| {
			/**
			 * Real collateralized trading (e.g., using ckUSDC, ICP).
			 */
			Settlement: null;
	  };
export type CancelFundWithdrawalError =
	{ PlanNotFound: null } | { InvalidPlanStatus: null } | { Common: CommonError };
export interface CancelFundWithdrawalParams {
	request_id: string;
}
export type CancelFundWithdrawalResult = { Ok: null } | { Err: CancelFundWithdrawalError };
/**
 * Input parameters for cancelling a limit order.
 */
export interface CancelLimitOrderParams {
	/**
	 * Unique identifier for the order to cancel.
	 */
	order_id: string;
}
/**
 * Configuration for a supported collateral asset.
 */
export interface CollateralAssetConfig {
	/**
	 * The number of decimal places defined by the underlying ledger.
	 */
	decimals: number;
	/**
	 * The underlying configuration required to interact with the asset's ledger.
	 */
	asset: Asset;
	/**
	 * Whether the asset is currently enabled for deposits.
	 */
	is_enabled: boolean;
	/**
	 * Balance domains where this asset may be deposited or withdrawn.
	 */
	allowed_balance_domains: Array<BalanceDomain>;
	/**
	 * Identifier of the oracle responsible for updating this asset's metrics.
	 */
	oracle_id: [] | [string];
	/**
	 * The canonical identifier for this asset within the clearing protocol.
	 */
	asset_id: string;
	/**
	 * The ticker symbol used for display purposes.
	 */
	symbol: string;
}
/**
 * Combined structure for public consumption of asset information.
 */
export interface CollateralAssetInfo {
	metrics: [] | [AssetMetrics];
	config: CollateralAssetConfig;
}
/**
 * Generic errors that can occur across multiple modules.
 */
export type CommonError =
	| {
			/**
			 * An unexpected internal error occurred.
			 */
			Internal: string;
	  }
	| {
			/**
			 * The input provided for the request is invalid.
			 */
			InvalidInput: string;
	  }
	| {
			/**
			 * A mathematical calculation resulted in an overflow or underflow.
			 */
			MathOverflow: null;
	  }
	| {
			/**
			 * The caller does not have permission to perform this action.
			 */
			Unauthorized: null;
	  }
	| {
			/**
			 * The registry canister principal has not been configured.
			 */
			RegistryNotSet: null;
	  };
/**
 * Global configuration for the Clearing canister.
 */
export interface Config {
	/**
	 * The global insurance fund fee ratio in basis points (1 bp = 0.01%).
	 */
	insurance_fund_fee_ratio: number;
	/**
	 * The comprehensive configuration for the internal accounting ledger (vUSD).
	 */
	internal_ledger: CollateralAssetConfig;
	/**
	 * The principal of the Chain Fusion Signer canister.
	 */
	signer_canister: Principal;
	/**
	 * The economic epoch version.
	 */
	version: number;
	/**
	 * The principal of the EVM RPC canister.
	 */
	evm_rpc: Principal;
	/**
	 * The global protocol fee ratio (Treasury) in basis points.
	 */
	protocol_fee_ratio: number;
}
/**
 * A generic representation of a decimal value with fixed precision.
 * This decouples numeric logic from domain-specific types like Price or Quantity.
 */
export interface DecimalValue {
	/**
	 * The number of decimal places (exponent).
	 */
	decimals: number;
	/**
	 * The numeric value (mantissa).
	 */
	value: bigint;
}
/**
 * Errors occurring during collateral deposit.
 */
export type DepositCollateralError =
	| {
			/**
			 * The asset is not permitted in this balance domain.
			 */
			DomainNotAllowed: { domain: BalanceDomain; asset_id: string };
	  }
	| {
			/**
			 * Overflow during collateral calculation.
			 */
			MathOverflow: null;
	  }
	| {
			/**
			 * An error occurred while interacting with the asset.
			 */
			Asset: AssetError;
	  };
/**
 * Input parameters for depositing collateral.
 */
export interface DepositCollateralParams {
	/**
	 * Unique identifier for the deposit operation.
	 */
	deposit_id: string;
	/**
	 * The specific balance domain to deposit into (defaults to Settlement).
	 */
	domain: [] | [BalanceDomain];
	/**
	 * The unique identifier of the asset to deposit.
	 */
	asset_id: string;
	/**
	 * The amount of the asset to deposit.
	 */
	amount: bigint;
}
/**
 * Outcome of a collateral deposit operation.
 */
export type DepositCollateralResult =
	| {
			/**
			 * Deposit was successfully planned or executed.
			 */
			Ok: null;
	  }
	| {
			/**
			 * Failed to process deposit.
			 */
			Err: DepositCollateralError;
	  };
/**
 * A multiformat description.
 * Provides multiple versions of the same content for different rendering environments.
 */
export interface Description {
	/**
	 * Optional HTML version of the description.
	 */
	html: [] | [string];
	/**
	 * Optional markdown version of the description.
	 */
	markdown: [] | [string];
	/**
	 * The mandatory plain text description.
	 */
	plain: string;
}
/**
 * Configurable policy for a balance domain.
 *
 * Controls domain-specific behavior such as fee ratios and feature flags.
 * Domains default to identical policies so risk enforcement is uniform unless overridden.
 */
export interface DomainPolicy {
	/**
	 * Whether deposits of real collateral assets are accepted in this domain.
	 */
	deposits_enabled: boolean;
	/**
	 * Optional override for the protocol fee ratio (bps).
	 * When `None`, the global `Config` value is used.
	 */
	protocol_fee_ratio_override: [] | [number];
	/**
	 * Human-readable label for this domain.
	 */
	label: string;
	/**
	 * Whether withdrawals of real collateral assets are allowed from this domain.
	 */
	withdrawals_enabled: boolean;
	/**
	 * Optional override for the insurance fund fee ratio (bps).
	 * When `None`, the global `Config` value is used.
	 */
	insurance_fund_fee_ratio_override: [] | [number];
}
/**
 * Represents an ERC-20 token on a specific EVM chain.
 */
export interface ErcToken {
	/**
	 * The number of decimals the token uses (e.g., 18 for ETH, 6 for USDC).
	 */
	decimals: number;
	/**
	 * The contract address of the token.
	 */
	token_address: string;
	/**
	 * The ID of the EVM chain where the token is deployed.
	 */
	chain_id: bigint;
}
/**
 * A recorded event in the clearing system.
 */
export interface Event {
	/**
	 * The quantity involved in the event.
	 */
	qty: bigint;
	/**
	 * The series ID associated with the event.
	 */
	series_id: string;
	/**
	 * The user associated with the event.
	 */
	user: Principal;
	/**
	 * Timestamp in nanoseconds since UNIX epoch.
	 */
	timestamp: bigint;
	/**
	 * Unique identifier for the event.
	 */
	event_id: bigint;
	/**
	 * The price at which the event occurred (if applicable).
	 */
	price: Price;
	/**
	 * The type of the event.
	 */
	event_type: EventType;
	/**
	 * The principal of the clearing canister.
	 */
	clearing_id: Principal;
}
/**
 * Categories of significant events in the clearing system.
 */
export type EventType =
	| {
			/**
			 * A new order was recorded.
			 */
			OrderPlaced: null;
	  }
	| {
			/**
			 * A trade was matched and executed.
			 */
			Executed: null;
	  }
	| {
			/**
			 * A position was liquidated due to insufficient margin.
			 */
			Liquidated: null;
	  }
	| {
			/**
			 * A series was settled.
			 */
			Settled: null;
	  };
export type FiatUnit = { Chf: null } | { Eur: null } | { Gbp: null } | { Usd: null };
/**
 * Input parameters for freezing a position to prepare for a cross-canister transfer.
 */
export interface FreezePositionForTransferParams {
	/**
	 * The specific outcome for categorical markets.
	 */
	outcome_id: [] | [string];
	/**
	 * The derivative series identifier.
	 */
	series_id: string;
	/**
	 * The user whose position is being frozen.
	 */
	user: Principal;
	/**
	 * Unique identifier for the transfer operation.
	 */
	transfer_id: string;
	/**
	 * Optional valuation price to include in the proof.
	 */
	valuation_price: [] | [Price];
}
export type FundType = { Insurance: null } | { Treasury: null };
/**
 * Input parameters for retrieving an account state.
 */
export interface GetAccountStateParams {
	/**
	 * The specific balance domain to query (defaults to Settlement if not provided).
	 */
	domain: [] | [BalanceDomain];
	/**
	 * Whether to force a recalculation of the margin status (e.g. refresh from ledgers).
	 */
	refresh: [] | [boolean];
}
/**
 * Outcome of an account state retrieval request.
 */
export type GetAccountStateResult =
	| {
			/**
			 * Successfully retrieved the account state details.
			 */
			Ok: AccountStateResponse;
	  }
	| {
			/**
			 * Failed to retrieve the account state.
			 */
			Err: AccountStateError;
	  };
export interface GetFundsResult {
	insurance_fund: Array<[string, bigint]>;
	treasury: Array<[string, bigint]>;
}
/**
 * Input parameters for retrieving a user's position in a series.
 */
export interface GetPositionParams {
	/**
	 * Optional outcome identifier for categorical markets.
	 */
	outcome_id: [] | [string];
	/**
	 * The derivative series identifier.
	 */
	series_id: string;
}
/**
 * Input parameters for
 * [`get_series_price_history`](super::get_series_price_history).
 *
 * Returns a series' executed trades aggregated into fixed-width
 * [`PriceHistoryInterval`] time buckets (OHLC + volume + trade count), so a
 * front end can render a time-scoped consensus/price chart directly instead of
 * fetching and re-bucketing the raw per-trade tape. The optional time bounds
 * let the caller request just the window it draws (e.g. the last day) and the
 * `interval` picks the resolution (hourly for short windows, daily for long).
 */
export interface GetSeriesPriceHistoryParams {
	/**
	 * Bucket width: one candle per hour or per day.
	 */
	interval: PriceHistoryInterval;
	/**
	 * The derivative series whose executed trades to aggregate.
	 */
	series_id: string;
	/**
	 * Exclusive upper bound on a trade's timestamp (ns). `None` runs through
	 * the series' latest trade.
	 */
	end_time: [] | [bigint];
	/**
	 * Inclusive lower bound on a trade's timestamp (ns). `None` starts from the
	 * series' earliest trade.
	 */
	start_time: [] | [bigint];
}
/**
 * Represents an incoming HTTP request to the canister.
 */
export interface HttpRequest {
	/**
	 * The URL of the request.
	 */
	url: string;
	/**
	 * The HTTP method (e.g., "GET", "POST").
	 */
	method: string;
	/**
	 * The request body.
	 */
	body: Uint8Array;
	/**
	 * The request headers.
	 */
	headers: Array<[string, string]>;
}
/**
 * Represents an HTTP response from the canister.
 */
export interface HttpResponse {
	/**
	 * The response body.
	 */
	body: Uint8Array;
	/**
	 * The response headers.
	 */
	headers: Array<[string, string]>;
	/**
	 * The HTTP status code.
	 */
	status_code: number;
}
/**
 * One principal's standing within a leaderboard window.
 *
 * The shape is intentionally an **aggregate**: it exposes only window totals
 * (net realized `PnL` plus the settled / win counts a front end needs for an
 * accuracy figure) and the principal's rank — never the per-series or
 * per-settlement breakdown.
 */
export interface LeaderboardEntry {
	principal: Principal;
	/**
	 * The principal's rank in the immediately preceding period (last week /
	 * last month), for ↑/↓ movement. `None` when the window has no prior
	 * period (all-time) or the principal did not appear in it.
	 */
	prior_rank: [] | [bigint];
	/**
	 * 1-based rank in the requested window, by net realized `PnL` descending.
	 * Competition ranking: principals with equal `PnL` share a rank, and the
	 * next distinct `PnL` skips the tied positions (e.g. `1, 2, 2, 4`).
	 */
	rank: bigint;
	/**
	 * Net realized `PnL` over the window, in internal USD (`vUSD`) base units —
	 * the signed sum of the principal's settlement cashflows.
	 */
	realized_pnl: bigint;
	/**
	 * Number of those settlements that were net positive. `win_count /
	 * settled_count` is the window accuracy.
	 */
	win_count: bigint;
	/**
	 * Number of settled positions in the window.
	 */
	settled_count: bigint;
}
/**
 * A page of ranked leaderboard standings.
 */
export interface LeaderboardPage {
	/**
	 * Total number of ranked principals in this window (after any `members`
	 * filter), so a front end can show "rank X of `total`" without paging to
	 * the end.
	 */
	total: bigint;
	/**
	 * When `Some`, pass back as `start_after` to fetch the next page. `None`
	 * means the last page has been returned.
	 */
	next_cursor: [] | [bigint];
	/**
	 * Entries for this page, in ascending rank (ties broken by principal for a
	 * stable order).
	 */
	items: Array<LeaderboardEntry>;
}
/**
 * The time window a leaderboard aggregates over.
 *
 * Windows are **fixed calendar periods**, not rolling spans, so each window
 * has a well-defined immediately-preceding period (the "prior window") for the
 * ↑/↓ rank deltas the front end renders:
 *
 * - [`Week`](LeaderboardWindow::Week): an ISO week — Monday 00:00:00 UTC through the following
 * Sunday. (Unix epoch day 0, 1970-01-01, was a Thursday, hence the `+ 3` Monday alignment
 * below.)
 * - [`Month`](LeaderboardWindow::Month): a calendar month in UTC.
 * - [`AllTime`](LeaderboardWindow::AllTime): a single, unbounded period covering every settlement.
 * Has no prior window.
 *
 * Calendar (rather than rolling) buckets were chosen because the prior-window
 * rank only has an unambiguous meaning against a discrete preceding period,
 * and because fixed buckets let the [`SETTLEMENT_LEADERBOARD`] index key on a
 * stable `(window, period_id)` pair maintained on the settlement write path.
 *
 * [`SETTLEMENT_LEADERBOARD`]: crate::memory::SETTLEMENT_LEADERBOARD
 */
export type LeaderboardWindow =
	| {
			/**
			 * All settlements ever, in one period.
			 */
			AllTime: null;
	  }
	| {
			/**
			 * Current ISO week (Monday–Sunday, UTC).
			 */
			Week: null;
	  }
	| {
			/**
			 * Current calendar month (UTC).
			 */
			Month: null;
	  };
/**
 * Represents a limit order stored in the clearing canister.
 */
export interface LimitOrder {
	/**
	 * Number of Series Units (contracts), where 1 unit represents exposure to 1.0 of the
	 * underlying asset. This value must always be positive; the direction (buy/long vs
	 * sell/short) is determined by the `side` field.
	 */
	qty: bigint;
	creator: Principal;
	outcome_id: [] | [string];
	/**
	 * Amount blocked in collateral (denominated in USD base units, see `USD_DECIMALS`).
	 */
	blocked_margin_usd: bigint;
	series_id: string;
	side: Side;
	order_id: string;
	/**
	 * Limit price in the precision defined by the associated series (`series.price_precision`).
	 */
	price: Price;
	/**
	 * The balance domain this order belongs to.
	 */
	balance_domain: BalanceDomain;
}
/**
 * Input parameters for [`list_leaderboard`](super::list_leaderboard).
 */
export interface ListLeaderboardParams {
	/**
	 * When set, rank **only** within this set of principals (a league /
	 * affiliation member set) instead of the whole population, and include
	 * every listed member — even those with no settlements in the window —
	 * with a zeroed aggregate, so the result covers the full league. When
	 * `None`, the global standings are returned and only principals that
	 * settled at least one position in the window appear.
	 *
	 * The set is caller-controlled and ranked in full, so it is capped at
	 * 10,000 principals — any realistic league is well under this; a longer
	 * list is truncated to the first 10,000.
	 */
	members: [] | [Array<Principal>];
	/**
	 * Which calendar window to rank: current week, current month, or all time.
	 */
	window: LeaderboardWindow;
	/**
	 * Exclusive pagination cursor: the number of leading entries already
	 * returned (i.e. the previous page's `next_cursor`). `None` starts from
	 * the top-ranked entry. Pagination is a snapshot over the window's ranked
	 * order, which is deterministic for a fixed underlying aggregate.
	 */
	start_after: [] | [bigint];
	/**
	 * Maximum number of entries to return. `None` returns all remaining
	 * entries; `0` is clamped to `1` so a paging caller always makes forward
	 * progress, mirroring the other clearing list queries.
	 */
	limit: [] | [bigint];
}
/**
 * Input parameters for listing active limit orders.
 */
export interface ListOrdersParams {
	/**
	 * Optional series identifier to filter orders.
	 */
	series_id: [] | [string];
}
/**
 * Input parameters for
 * [`list_series_settlement_statuses`](super::list_series_settlement_statuses).
 *
 * Batches the per-series settlement check a resolution solver would otherwise
 * make one call at a time. Callers pass the (bounded) set of series they care
 * about — typically the "due" candidates from the registry — and receive one
 * status per id in request order. Unknown or still-open series come back with a
 * `None` status. The read looks each id up in `SETTLEMENT_PLANS`, so the work is
 * `O(#series_ids)` regardless of how many plans exist. Mirrors
 * [`ListSeriesTradedVolumesParams`](crate::api::trade::params::ListSeriesTradedVolumesParams).
 */
export interface ListSeriesSettlementStatusesParams {
	/**
	 * The series to check. Results are returned one per id, in this order.
	 */
	series_ids: Array<string>;
}
/**
 * Input parameters for
 * [`list_series_trade_history`](super::list_series_trade_history).
 *
 * Returns the market-wide executed-trade history for a single series so a
 * front end can derive a price-history series (e.g. a YES-probability
 * sparkline) from the per-trade `price`/`timestamp`. Unlike `get_trade_history`
 * the result is not caller-scoped.
 */
export interface ListSeriesTradeHistoryParams {
	/**
	 * The derivative series whose executed trades to return.
	 */
	series_id: string;
	/**
	 * Resume after this trade's `event_id` (exclusive). `None` starts from the
	 * earliest executed trade. Pass the previous response's `next_cursor` to
	 * continue. Executed-trade `event_id`s are strictly increasing in
	 * execution order, so the bare id is a stable cursor.
	 */
	start_after: [] | [bigint];
	/**
	 * Maximum number of trades to return. `None` returns all remaining trades.
	 */
	limit: [] | [bigint];
}
/**
 * Input parameters for
 * [`list_series_traded_volumes`](super::list_series_traded_volumes).
 *
 * Totals each series' market-wide traded volume in one call so a front end can
 * label a page of market cards without a per-card round-trip. Unknown or
 * untraded ids simply total zero. Callers should request a bounded page of
 * series (the set they render): the read sums each series' trade tape, so the
 * work scales with the trades on the requested series.
 */
export interface ListSeriesTradedVolumesParams {
	/**
	 * The series to total. Results are returned one per id, in this order.
	 */
	series_ids: Array<string>;
}
/**
 * Input parameters for [`list_settled_series`](super::list_settled_series).
 *
 * A series is considered settled the moment a settlement plan is opened for it
 * (any [`PlanStatus`](crate::types::plans::PlanStatus)), which is also when it
 * stops being tradeable. Front ends use this to subtract the resolved set from
 * the registry's open/unexpired catalog page.
 */
export interface ListSettledSeriesParams {
	/**
	 * Resume after this series id (exclusive). `None` starts from the lowest
	 * series id. Settled series ids are returned in ascending order, so paging
	 * with the previous response's `next_cursor` is stable.
	 */
	start_after: [] | [string];
	/**
	 * Maximum number of ids to return. `None` returns all remaining ids.
	 */
	limit: [] | [bigint];
	/**
	 * When set, only return settled series whose plan recorded this balance
	 * domain. Lets a caller scoped to one domain (e.g. a flow deck) shrink the
	 * response to the relevant subset.
	 */
	balance_domain: [] | [BalanceDomain];
}
export interface MigrateDomainParams {
	from_domain: BalanceDomain;
	migration_id: string;
	to_domain: BalanceDomain;
}
export type MigrateDomainResult = { Ok: null } | { Err: MigrationError };
export type MigrationError =
	| { NoStateTOMigrate: null }
	| { SameDomain: null }
	| { InFlightPlansExist: null }
	| { Common: CommonError };
/**
 * Represents a native asset on an EVM-compatible chain
 * (for example ETH on Ethereum/Base, POL on Polygon, or BNB on BSC).
 */
export interface NativeEvmAsset {
	/**
	 * The number of decimals the native asset uses.
	 */
	decimals: number;
	/**
	 * The EVM chain where this native asset is used.
	 */
	chain_id: bigint;
}
export type NonMonetaryUnit = { Points: null } | { Social: SocialReward };
/**
 * Metadata for a specific outcome in a categorical market.
 */
export interface Outcome {
	/**
	 * The unique identifier of the outcome.
	 */
	id: string;
	/**
	 * A short title for the outcome (e.g., "Yes", "No", "Team A").
	 */
	title: string;
	/**
	 * An optional detailed description of the outcome.
	 */
	description: [] | [Description];
	/**
	 * An optional icon URL for the outcome.
	 */
	icon_url: [] | [string];
}
/**
 * Aggregate lean of the supplied principal set on a single outcome of a
 * series.
 *
 * Carries **counts only** — no principal identities, sides, quantities, or
 * P&L. Long is the number of net-long holders, short the number of net-short
 * holders; flat (zero net) positions are excluded from both.
 */
export interface OutcomeLean {
	/**
	 * `long + short`, the number of supplied principals with a non-flat
	 * position on this outcome.
	 */
	total: bigint;
	/**
	 * The outcome this lean is for. `None` is the series' binary payoff (long
	 * vs short); `Some` identifies a categorical outcome.
	 */
	outcome_id: [] | [string];
	/**
	 * Number of supplied principals net long on this outcome.
	 */
	long: bigint;
	/**
	 * Number of supplied principals net short on this outcome.
	 */
	short: bigint;
}
/**
 * Mechanism for ensuring idempotency in ledger payments.
 */
export type PaymentIdempotency = {
	/**
	 * Uses the ICRC `created_at_time` field to prevent duplicate transfers.
	 */
	IcrcCreatedAtTimeNs: bigint;
};
/**
 * Defines the payoff structure for a derivative contract.
 */
export type PayoffType =
	| {
			/**
			 * Payoff based on the positive difference between strike and underlying price.
			 */
			Put: null;
	  }
	| {
			/**
			 * A fixed payoff if the condition is met (all-or-nothing).
			 */
			Binary: null;
	  }
	| {
			/**
			 * Payoff based on the positive difference between underlying price and strike.
			 */
			Call: null;
	  }
	| {
			/**
			 * A categorical market with multiple mutually exclusive outcomes.
			 */
			Categorical: null;
	  };
export type PayoutUnit = { Fiat: FiatUnit } | { Asset: Asset } | { NonMonetary: NonMonetaryUnit };
/**
 * The execution status of a background operation plan.
 */
export type PlanStatus =
	| {
			/**
			 * The plan has been successfully completed.
			 */
			Finalised: null;
	  }
	| {
			/**
			 * The plan is created but execution has not started.
			 */
			Planned: null;
	  }
	| {
			/**
			 * The plan is currently being executed.
			 */
			Executing: null;
	  };
/**
 * Represents an open position in a derivative series for a specific user.
 */
export interface Position {
	/**
	 * The specific outcome for categorical markets.
	 */
	outcome_id: [] | [string];
	/**
	 * The unique identifier of the derivative series.
	 */
	series_id: string;
	/**
	 * The net quantity of the position (positive for Long, negative for Short).
	 */
	net_qty: bigint;
	/**
	 * The user who owns the position.
	 */
	user: Principal;
	/**
	 * The amount of margin reserved for this specific position in USD.
	 */
	reserved_margin_usd: bigint;
}
/**
 * A cryptographically signed proof of an open position, used for cross-canister transfers.
 */
export interface PositionProof {
	/**
	 * The quantity of the position.
	 */
	qty: bigint;
	/**
	 * The cryptographic signature of the proof data.
	 */
	signature: Uint8Array;
	/**
	 * The specific outcome for categorical markets.
	 */
	outcome_id: [] | [string];
	/**
	 * The unique identifier of the derivative series.
	 */
	series_id: string;
	/**
	 * The user whose position is being proven.
	 */
	user: Principal;
	/**
	 * Unique identifier for the transfer operation.
	 */
	transfer_id: string;
	/**
	 * Optional valuation price for the position.
	 */
	valuation_price: [] | [Price];
	/**
	 * The principal of the clearing canister that issued the proof.
	 */
	clearing_id: Principal;
}
/**
 * Encapsulates a price with its numerical value and domain-specific metadata.
 * Decouples the mathematical representation (`DecimalValue`) from the
 * reporting context (timestamp, oracle Source).
 */
export interface Price {
	/**
	 * Optional timestamp when this price was generated/observed.
	 */
	timestamp: [] | [bigint];
	/**
	 * Optional identifier for the oracle source.
	 */
	oracle_id: [] | [string];
	/**
	 * The numeric component of the price.
	 */
	decimal: DecimalValue;
}
/**
 * The fixed-width time bucket a [`get_series_price_history`] call aggregates a
 * series' executed trades into.
 *
 * Buckets are **fixed-width and epoch-aligned** (each bucket is `[k * width,
 * (k + 1) * width)` ns since the Unix epoch), not rolling spans, so the same
 * instant always falls in the same bucket regardless of when the query runs —
 * two calls over an overlapping range return byte-identical candles for the
 * shared buckets. Hourly resolution backs the short windows the front end
 * renders (1d / 7d) and daily resolution the long ones (30d / all) without the
 * caller having to fetch and re-bucket the raw per-trade tape.
 *
 * [`get_series_price_history`]: crate::api::trade::get_series_price_history
 */
export type PriceHistoryInterval =
	| {
			/**
			 * One candle per UTC day.
			 */
			Day: null;
	  }
	| {
			/**
			 * One candle per UTC hour.
			 */
			Hour: null;
	  };
export type RefreshIcrcAssetMetadataError =
	{ AssetNotFound: null } | { NotAnIcrcAsset: null } | { Common: CommonError };
export interface RefreshIcrcAssetMetadataParams {
	asset_id: string;
}
export type RefreshIcrcAssetMetadataResult = { Ok: null } | { Err: RefreshIcrcAssetMetadataError };
export type RegisterIcrcAssetError =
	| {
			/**
			 * `allowed_balance_domains` was empty or could not be normalized.
			 */
			InvalidAllowedBalanceDomains: null;
	  }
	| { AssetAlreadyExists: null }
	| { VusdCannotBeCollateral: null }
	| { Common: CommonError };
export interface RegisterIcrcAssetParams {
	haircut_bps: number;
	is_enabled: boolean;
	/**
	 * Non-empty. Duplicates are removed. Order is normalized for stable storage.
	 */
	allowed_balance_domains: Array<BalanceDomain>;
	ledger_id: Principal;
	oracle_id: [] | [string];
	asset_id: string;
}
export type RegisterIcrcAssetResult = { Ok: null } | { Err: RegisterIcrcAssetError };
/**
 * Settlement terms for a series. Compulsory on every market.
 *
 * Modeled as a struct (not a bare `String`) so it can grow without a breaking
 * candid change: future fields — e.g. structured `rules` (named source +
 * settle date + day-count, see issue #64) — are added as `opt` fields, which
 * candid can decode against records persisted before the field existed.
 * Variants were considered and rejected: adding an enum variant risks decode
 * failures in already-deployed consumers, whereas appending `opt` record
 * fields is forward-compatible.
 */
export interface Resolution {
	/**
	 * Human-readable clause describing how the market settles.
	 */
	clause: string;
}
/**
 * Defines a specific derivative series (contract).
 */
export interface Series {
	/**
	 * A short, descriptive title for the series.
	 */
	title: string;
	/**
	 * Target price for options, if applicable.
	 */
	strike: [] | [Price];
	/**
	 * The principal identifier of the series creator.
	 */
	creator: Principal;
	/**
	 * The mathematical payoff model used for this series.
	 */
	payoff_type: PayoffType;
	/**
	 * The Engine that created this series, if any.
	 * `None` for series created directly by a canister controller.
	 */
	engine_id: [] | [string];
	/**
	 * The unit in which the contract payoff is expressed.
	 */
	payout_unit: PayoutUnit;
	/**
	 * Expiry timestamp in nanoseconds since UNIX epoch.
	 */
	expiry_ns: bigint;
	/**
	 * An optional banner URL for the market.
	 */
	banner_url: [] | [string];
	/**
	 * Optional timestamp in nanoseconds since UNIX epoch at which trading opens.
	 *
	 * `None` means the series is tradeable from the moment it is registered —
	 * the historical behavior, and the canonical way to express "live now".
	 * `Some(t)` schedules the series: it is listed and discoverable immediately
	 * but trading is rejected until `t`. The window is inclusive at the open
	 * (`now >= start_ns` is live) and exclusive at the close (`now < expiry_ns`
	 * is unexpired), so a series is tradeable over `[start_ns, expiry_ns)`.
	 *
	 * Participates in `series_id` hashing (see [`Series::generate_id`]): two
	 * series that differ only in their trading window are distinct contracts,
	 * so a scheduled series can never silently collide with an already-live one
	 * and inherit a start date its creator did not ask for. To keep that
	 * guarantee meaningful `None` is the only encoding of "already live" —
	 * `add_series` rejects a `start_ns` at or before the current time, so the
	 * same market cannot exist under two ids.
	 */
	start_ns: [] | [bigint];
	/**
	 * Unique identifier computed from series parameters.
	 */
	series_id: string;
	/**
	 * The underlying asset ticker or identifier (e.g., "ICP/USD").
	 */
	underlying: string;
	/**
	 * Optional [BCP 47](https://www.rfc-editor.org/info/bcp47) language tag
	 * describing the language of `title`, `description`, and any
	 * `outcomes[].title` / `outcomes[].description`.
	 *
	 * Examples: `"en"`, `"en-US"`, `"es"`, `"zh-Hant-HK"`.
	 *
	 * `locale` is metadata: it does NOT participate in `series_id` hashing,
	 * so the same economic contract written in different languages must
	 * collide on the same id (otherwise liquidity would fragment across
	 * localized clones of the same market).
	 *
	 * When `None`, consumers should assume the default locale `"en"` and are
	 * responsible for translating into the user's preferred locale — the
	 * canister never stores translations on-chain.
	 */
	locale: [] | [string];
	/**
	 * A detailed description of the series.
	 */
	description: Description;
	/**
	 * The settlement terms describing how this market resolves.
	 *
	 * Compulsory metadata: every series carries resolution terms. Like
	 * `title`/`description`/`locale`, it does NOT participate in `series_id`
	 * hashing (see [`Series::generate_id`]), so the same economic contract
	 * keeps a single id regardless of its resolution wording.
	 */
	resolution: Resolution;
	/**
	 * The defined outcomes for categorical markets (ordered).
	 */
	outcomes: [] | [Array<Outcome>];
	/**
	 * Timestamp of series creation in nanoseconds since UNIX epoch.
	 */
	created_at_ns: bigint;
	/**
	 * An optional icon URL for the market.
	 */
	icon_url: [] | [string];
	/**
	 * The set of trading access policies governing who may trade this series.
	 * **Must never be empty** — every series carries at least one policy.
	 *
	 * Evaluated as a logical OR: a caller is authorized if **any** policy
	 * in the list grants them access.
	 *
	 * - `[Open]` → explicitly unrestricted (default).
	 * - `[Restricted { groups }]` → only group members may trade.
	 * - Multiple policies can coexist (e.g. `[Open, Restricted { groups }]`).
	 */
	trading_access: Array<TradingAccess>;
	/**
	 * The canonical number of decimals used for prices and strikes in this series.
	 */
	price_precision: number;
	/**
	 * The domain this market belongs to (e.g. Playground, Settlement).
	 */
	balance_domain: BalanceDomain;
	/**
	 * The identifier of the oracle providing the settlement data.
	 */
	oracle_source: string;
	/**
	 * If this series was forked from another, the source series ID.
	 */
	forked_from: [] | [string];
}
/**
 * One aggregated price-history candle: every executed trade on a series whose
 * timestamp falls in a single fixed-width bucket, summarized into the
 * open/high/low/close + volume a chart plots.
 *
 * `close` is the bucket's consensus the front end maps to a 0..1 YES
 * probability (the last trade price in the bucket); `open`/`high`/`low` let it
 * draw candles. Prices on one series share the series' precision, so `high` and
 * `low` are the per-bucket max and min by numeric value.
 */
export interface SeriesPriceCandle {
	/**
	 * Lowest trade price in the bucket.
	 */
	low: Price;
	/**
	 * Highest trade price in the bucket.
	 */
	high: Price;
	/**
	 * Price of the last trade in the bucket (latest timestamp, ties broken by
	 * execution order) — the consensus a sparkline/chart plots.
	 */
	close: Price;
	/**
	 * Price of the first trade in the bucket (earliest timestamp, ties broken
	 * by execution order).
	 */
	open: Price;
	/**
	 * Total traded quantity in the bucket (sum of each trade's positive `qty`).
	 */
	volume: bigint;
	/**
	 * Number of executed trades in the bucket.
	 */
	trade_count: bigint;
	/**
	 * Start of the bucket (ns since the Unix epoch); see
	 * [`PriceHistoryInterval::bucket_start`]. Candles are returned ascending by
	 * this field.
	 */
	bucket_start_ns: bigint;
}
/**
 * A series' executed-trade history aggregated into fixed-width time buckets.
 */
export interface SeriesPriceHistory {
	/**
	 * Buckets that contain at least one trade, ascending by `bucket_start_ns`.
	 * Empty buckets are omitted (the series simply had no trades then), so a
	 * young or untraded market returns an empty vector rather than fabricated
	 * points.
	 */
	candles: Array<SeriesPriceCandle>;
}
/**
 * One series' settlement status, paired with the id it was requested for.
 *
 * `status` is `Some` when a settlement plan exists for the series (in any
 * [`PlanStatus`](crate::types::plans::PlanStatus) — a plan is opened the moment
 * settlement begins) and `None` otherwise. A `None` covers both a still-open
 * series and an unknown id; the two are not distinguished here. The `series_id`
 * is echoed on each entry so callers can align results with their requested ids
 * and attribute a `None`, which carries no id of its own.
 */
export interface SeriesSettlementStatus {
	/**
	 * The settlement progress, or `None` if the series has no settlement plan
	 * yet (still open / not being settled).
	 */
	status: [] | [SettlementStatusView];
	/**
	 * The series this status is for (echoes the requested id).
	 */
	series_id: string;
}
/**
 * A page of executed trades scoped to a single series.
 */
export interface SeriesTradeHistoryPage {
	/**
	 * When `Some`, pass back as `start_after` to fetch the next page (it is the
	 * `event_id` of the last trade returned). `None` means the last page has
	 * been returned.
	 */
	next_cursor: [] | [bigint];
	/**
	 * Executed trades for the series in this page, one point per trade, ordered
	 * by `event_id` ascending (i.e. execution order).
	 */
	items: Array<SeriesTradePoint>;
}
/**
 * A single executed trade on a series, as surfaced by the market-wide
 * price-history query.
 *
 * Each executed trade emits two [`Event`] rows (one per counterparty) that
 * share the same `event_id`, `price`, and `timestamp`. A price history needs
 * only one point per trade, so this collapses the pair to the trade-level
 * facts a front end plots — `price`/`timestamp` for the sparkline, `qty` for
 * optional volume — without exposing either counterparty's principal in a
 * market-wide read.
 */
export interface SeriesTradePoint {
	/**
	 * Traded quantity (positive).
	 */
	qty: bigint;
	/**
	 * Execution timestamp in nanoseconds since UNIX epoch.
	 */
	timestamp: bigint;
	/**
	 * Id of the trade's [`Event`] rows. Strictly increasing in execution
	 * order, so it doubles as the pagination cursor.
	 */
	event_id: bigint;
	/**
	 * Execution price of the trade.
	 */
	price: Price;
}
/**
 * One series' cumulative market-wide traded volume.
 *
 * `volume` is the traded *notional* — the sum over executed trades of
 * `qty · price`, the value that changed hands — in USD base units (the
 * `USD_DECIMALS` scale), not a contract count. `trade_count` is the number of
 * executed trades. An untraded or unknown series totals zero on both.
 */
export interface SeriesTradedVolume {
	/**
	 * The series these totals are for (echoes the requested id).
	 */
	series_id: string;
	/**
	 * Cumulative traded notional (sum of `qty · price`) in USD base units.
	 */
	volume: bigint;
	/**
	 * Number of executed trades on the series.
	 */
	trade_count: bigint;
}
/**
 * Input parameters for initiating a series settlement.
 */
export interface SettleSeriesParams {
	/**
	 * The derivative series identifier.
	 */
	series_id: string;
	/**
	 * The final settlement data from the oracle.
	 */
	settlement: SettlementInput;
}
/**
 * Outcome of a derivative series settlement request.
 */
export type SettleSeriesResult =
	| {
			/**
			 * Settlement plan was successfully created and all processing is complete.
			 */
			Ok: null;
	  }
	| {
			/**
			 * Failed to initiate settlement.
			 */
			Err: SettlementError;
	  }
	| {
			/**
			 * The settlement is in progress but incomplete due to processing limits.
			 * The caller should call `settle_series` again to continue.
			 */
			Processing: null;
	  };
/**
 * A page of settled (resolved) series ids.
 */
export interface SettledSeriesPage {
	/**
	 * When `Some`, pass back as `start_after` to fetch the next page. `None`
	 * means the last page has been returned.
	 */
	next_cursor: [] | [string];
	/**
	 * Settled series ids in this page, ascending.
	 */
	items: Array<string>;
}
/**
 * One principal's settled-position accuracy over a requested window.
 *
 * Mirrors the aggregate-only contract of [`LeaderboardEntry`]: window totals
 * (settled / win counts plus net realized `PnL`) and never a per-settlement
 * breakdown. `win_count / settled_count` is the window accuracy. Only
 * principals with at least one settlement in the window are returned — a
 * member with no settlement contributes nothing to a cohort's accuracy, and
 * the caller already knows the full set it asked for.
 */
export interface SettlementAccuracyEntry {
	principal: Principal;
	/**
	 * Net realized `PnL` over the window, in internal USD (`vUSD`) base units —
	 * the signed sum of the principal's settlement cashflows.
	 */
	realized_pnl: bigint;
	/**
	 * Number of those settlements that were net positive (`cashflow_usd > 0`).
	 */
	win_count: bigint;
	/**
	 * Number of settled positions in the window.
	 */
	settled_count: bigint;
}
/**
 * Errors occurring during derivative series settlement.
 */
export type SettlementError =
	| {
			/**
			 * A second `settle_series` call arrived with a `SettlementInput` that does
			 * not match the one already locked in by the in-flight plan.
			 *
			 * Covers both `Price` and `Outcome` settlement types: the variant that's
			 * locked is stored in `existing`, and the one just attempted is in
			 * `requested`. Callers that need to surface a human-readable diff can
			 * pattern-match on both variants without losing information.
			 */
			InconsistentSettlement: {
				requested: SettlementInput;
				existing: SettlementInput;
			};
	  }
	| {
			/**
			 * Overflow during settlement calculation.
			 */
			MathOverflow: null;
	  }
	| {
			/**
			 * Total net payoffs (post-fee) exceed global system equity (system insolvency).
			 */
			SolvencyViolation: {
				total_net_payoff: bigint;
				total_collateral_usd: bigint;
			};
	  }
	| {
			/**
			 * An error occurred while interacting with the asset.
			 */
			Asset: AssetError;
	  }
	| {
			/**
			 * A common error occurred.
			 */
			Common: CommonError;
	  };
/**
 * Input data for settling a series.
 */
export type SettlementInput =
	| {
			/**
			 * Final price for scalar markets (Binary, Call, Put).
			 */
			Price: Price;
	  }
	| {
			/**
			 * Resolved winner for categorical markets.
			 */
			Outcome: string;
	  };
/**
 * A plan for processing a derivative series settlement in the background.
 */
export interface SettlementPlan {
	/**
	 * Current execution status of the plan.
	 */
	status: PlanStatus;
	/**
	 * Base idempotency key in nanoseconds.
	 */
	idempotency_ns: PaymentIdempotency;
	/**
	 * The unique identifier of the derivative series.
	 */
	series_id: string;
	/**
	 * The protocol fee (in USD units).
	 */
	fee_usd: bigint;
	/**
	 * Tracks progress through accounting updates.
	 */
	accounting_cursor: bigint;
	/**
	 * The insurance fee (in USD units).
	 */
	insurance_fee_usd: bigint;
	/**
	 * Detailed position snapshots and accounting updates.
	 */
	positions: Array<SettlementPosition>;
	/**
	 * Whether all accounting updates have been applied to account states.
	 */
	accounting_applied: boolean;
	/**
	 * The domain of the series being settled.
	 */
	balance_domain: BalanceDomain;
	/**
	 * The oracle source identifier for authorization.
	 */
	oracle_source: string;
	/**
	 * The final settlement data.
	 */
	settlement: SettlementInput;
}
/**
 * Snapshot of a single user's position and its settlement accounting.
 */
export interface SettlementPosition {
	outcome_id: [] | [string];
	net_qty: bigint;
	user: Principal;
	reserved_margin_usd: bigint;
	cashflow_usd: bigint;
}
/**
 * Public settlement progress for a derivative series.
 */
export interface SettlementStatusView {
	status: PlanStatus;
	series_id: string;
	fee_usd: bigint;
	accounting_cursor: bigint;
	insurance_fee_usd: bigint;
	accounting_applied: boolean;
	balance_domain: BalanceDomain;
	oracle_source: string;
	total_positions: bigint;
	settlement: SettlementInput;
}
/**
 * Represents the side of an order or trade.
 */
export type Side = { Buy: null } | { Sell: null };
export interface SocialReward {
	/**
	 * A short title for the reward (e.g., "Pizza 🍕").
	 */
	title: string;
	/**
	 * An optional detailed description of the reward.
	 */
	description: [] | [string];
	/**
	 * An optional icon URL for the reward.
	 */
	icon_url: [] | [string];
}
/**
 * Represents structured statistics for the clearing system.
 */
export interface Stats {
	/**
	 * Total number of unique margin accounts.
	 */
	total_users: bigint;
	/**
	 * Total collateral balance in margin accounts per asset.
	 */
	margin_balances: Array<[Asset, bigint]>;
	/**
	 * Total collateral locked across all positions.
	 */
	total_collateral_locked: bigint;
	/**
	 * Total number of executed trades.
	 */
	total_trades: bigint;
	/**
	 * Total number of derivative series.
	 */
	total_series: bigint;
	/**
	 * Total absolute open interest across all series.
	 */
	open_interest: bigint;
	/**
	 * Total number of events per type.
	 */
	event_counts: Array<[string, bigint]>;
}
/**
 * Input parameters for submitting a limit order.
 */
export interface SubmitLimitOrderParams {
	/**
	 * The quantity of the order. Must be positive.
	 */
	qty: bigint;
	/**
	 * The specific outcome for categorical markets.
	 */
	outcome_id: [] | [string];
	/**
	 * The derivative series identifier.
	 */
	series_id: string;
	/**
	 * The side of the order (Buy or Sell).
	 */
	side: Side;
	/**
	 * Unique identifier for the order.
	 */
	order_id: string;
	/**
	 * The limit price of the order.
	 */
	price: Price;
}
/**
 * Input parameters for submitting a market order (taking an existing limit order).
 */
export interface SubmitMarketOrderParams {
	/**
	 * Optional taker quantity. Must be positive when provided. The trade executes for
	 * `min(qty, resting order qty)` and the unfilled remainder stays on the book with
	 * proportionally reduced blocked margin. `None` fills the entire resting order.
	 */
	qty: [] | [bigint];
	/**
	 * Unique identifier for the trade resulting from this match.
	 */
	trade_id: string;
	/**
	 * The identifier of the limit order to be matched.
	 */
	matching_order_id: string;
}
/**
 * Input parameters for submitting a matched trade from an exchange.
 */
export interface SubmitMatchedTradeParams {
	/**
	 * The quantity of the trade. Must be positive.
	 */
	qty: bigint;
	/**
	 * Unique identifier for the trade provided by the exchange.
	 */
	trade_id: string;
	/**
	 * The specific outcome for categorical markets.
	 */
	outcome_id: [] | [string];
	/**
	 * The derivative series identifier.
	 */
	series_id: string;
	/**
	 * The user opening or increasing a Short position (seller).
	 */
	seller: Principal;
	/**
	 * Optional amount to atomically unblock for the buyer.
	 */
	buyer_unblock_amount: [] | [bigint];
	/**
	 * The user opening or increasing a Long position (buyer).
	 */
	buyer: Principal;
	/**
	 * The execution price of the trade.
	 */
	price: Price;
	/**
	 * Optional amount to atomically unblock for the seller.
	 */
	seller_unblock_amount: [] | [bigint];
}
/**
 * Outcome of a matched trade submission.
 */
export type SubmitMatchedTradeResult =
	| {
			/**
			 * Returns `true` if the trade was successfully processed.
			 */
			Ok: boolean;
	  }
	| {
			/**
			 * Failed to submit or match the trade.
			 */
			Err: TradeError;
	  };
/**
 * Errors occurring during trade submission or matching.
 */
export type TradeError =
	| {
			/**
			 * A user tried to trade with themselves.
			 */
			SelfTradingNotAllowed: null;
	  }
	| {
			/**
			 * The specified order was not found.
			 */
			OrderNotFound: string;
	  }
	| {
			/**
			 * The series is scheduled and its trading window has not opened yet, so no
			 * trades, orders, or transfers can be initiated on it.
			 *
			 * Returned whenever a trade-initiating path sees a series whose `start_ns`
			 * is still in the future. Carries the open so the caller can render a
			 * countdown or retry at the right moment instead of polling blindly.
			 */
			SeriesNotStarted: {
				/**
				 * The timestamp (nanoseconds since the UNIX epoch) at which it opens.
				 */
				start_ns: bigint;
				/**
				 * The series that is not yet open.
				 */
				series_id: string;
			};
	  }
	| {
			/**
			 * The trade would violate the no-arbitrage principle (e.g., sum of outcome prices > 1.0).
			 */
			ArbitrageLimitExceeded: {
				/**
				 * The hard limit (usually 1.0 USD).
				 */
				limit_usd: bigint;
				/**
				 * The current sum of best bids across all outcomes.
				 */
				sum_usd: bigint;
			};
	  }
	| {
			/**
			 * Failed to communicate with the registry canister.
			 */
			RegistryError: string;
	  }
	| {
			/**
			 * The series' trading window has closed, so no new exposure can be opened
			 * on it.
			 *
			 * Returned to exposure-opening paths only. Redeeming a complete set and
			 * accepting a transferred position stay available after expiry, because they
			 * only release exposure that already exists and settlement may not run for
			 * some time after the window closes.
			 */
			SeriesExpired: {
				/**
				 * The timestamp (nanoseconds since the UNIX epoch) at which it closed.
				 */
				expiry_ns: bigint;
				/**
				 * The series whose window has closed.
				 */
				series_id: string;
			};
	  }
	| {
			/**
			 * The user has insufficient margin to open or maintain the position.
			 */
			InsufficientMargin: {
				/**
				 * Current margin balance.
				 */
				balance: bigint;
				/**
				 * The user whose margin is insufficient.
				 */
				user: Principal;
				/**
				 * Required margin for the trade.
				 */
				required: bigint;
			};
	  }
	| {
			/**
			 * The caller is not the creator of the order.
			 */
			NotOrderCreator: null;
	  }
	| {
			/**
			 * The specified series was not found in the registry.
			 */
			SeriesNotFound: string;
	  }
	| {
			/**
			 * The series has an active or finalised settlement plan, so no new
			 * trades, orders, or transfers can be initiated on it.
			 *
			 * Returned whenever a trade-initiating path sees an entry in
			 * `SETTLEMENT_PLANS` for the series. Once a series is settled it is
			 * economically closed: positions are gone, winners' cash is booked,
			 * and opening a new position could only create unbacked exposure.
			 */
			SeriesAlreadySettled: string;
	  }
	| {
			/**
			 * The caller is not authorized to trade on this restricted series.
			 *
			 * Returned when a series carries `TradingAccess::Restricted` policies
			 * and the caller is not a member of any of the referenced groups.
			 * The caller should check `is_trading_authorized` on the registry
			 * or contact the group creator to be added as a member.
			 */
			NotAuthorizedToTrade: null;
	  }
	| {
			/**
			 * A common error occurred.
			 */
			Common: CommonError;
	  };
/**
 * A single trading access policy attached to a derivative series.
 *
 * A [`Series`](super::series::Series) holds a `Vec<TradingAccess>`.
 * Authorization is evaluated as a logical **OR** across all policies:
 * if *any* policy in the list grants access to the caller, the caller
 * may trade.
 *
 * # Invariant
 *
 * The `trading_access` vector on a [`Series`](super::series::Series) **must
 * never be empty**. Every series must carry at least one policy. The default
 * is `[Open]`. This invariant is enforced at the API level: `add_series`
 * fills `[Open]` if empty, and `update_trading_access` rejects empty lists.
 *
 * # Combining policies
 *
 * A series may carry multiple policies simultaneously. For example:
 * - `[Open]` — open to everyone (default).
 * - `[Restricted { groups: [g1, g2] }]` — only members of g1 or g2.
 * - `[Open, Restricted { groups: [g1] }]` — open to everyone *and* additionally tagged as
 * belonging to g1 (useful for discovery/UI filtering).
 *
 * # Extensibility
 *
 * New variants (e.g. `TokenGated`, `ReputationBased`) can be added in
 * the future without breaking existing policies or on-chain state.
 */
export type TradingAccess =
	| {
			/**
			 * Unrestricted: any authenticated (non-anonymous) caller can trade.
			 */
			Open: null;
	  }
	| {
			/**
			 * Restricted to members of the specified groups.
			 * The caller is authorized if they belong to **at least one** of the
			 * listed groups.
			 */
			Restricted: {
				/**
				 * The group IDs whose members are allowed to trade.
				 */
				groups: Array<string>;
			};
	  };
export interface UpdateAssetMetricsParams {
	metrics: AssetMetrics;
	asset_id: string;
}
export type UpdateAssetPriceError =
	| { AssetNotFound: null }
	| { AssetMetricsNotInitialized: null }
	| { OracleNotConfigured: null }
	| { Common: CommonError };
export interface UpdateAssetPriceParams {
	price: Price;
	asset_id: string;
}
export type UpdateAssetPriceResult = { Ok: null } | { Err: UpdateAssetPriceError };
export type UpdateCollateralAllowedDomainsError =
	{ AssetNotFound: null } | { InvalidAllowedBalanceDomains: null };
export interface UpdateCollateralAllowedDomainsParams {
	allowed_balance_domains: Array<BalanceDomain>;
	asset_id: string;
}
export type UpdateCollateralAllowedDomainsResult =
	{ Ok: null } | { Err: UpdateCollateralAllowedDomainsError };
export interface UpdateCollateralAssetParams {
	config: CollateralAssetConfig;
}
export interface UpdateDomainPolicyParams {
	domain: BalanceDomain;
	policy: DomainPolicy;
}
/**
 * Errors occurring during collateral withdrawal.
 */
export type WithdrawCollateralError =
	| {
			/**
			 * The user does not have enough excess margin to withdraw the requested amount.
			 */
			InsufficientExcessMargin: {
				/**
				 * The amount requested to be withdrawn.
				 */
				requested: bigint;
				/**
				 * Current excess margin available for withdrawal.
				 */
				available: bigint;
			};
	  }
	| {
			/**
			 * The asset is not permitted in this balance domain.
			 */
			DomainNotAllowed: { domain: BalanceDomain; asset_id: string };
	  }
	| {
			/**
			 * Overflow during collateral calculation.
			 */
			MathOverflow: null;
	  }
	| {
			/**
			 * An error occurred while interacting with the asset.
			 */
			Asset: AssetError;
	  };
/**
 * Input parameters for withdrawing collateral.
 */
export interface WithdrawCollateralParams {
	/**
	 * The specific balance domain to withdraw from (defaults to Settlement).
	 */
	domain: [] | [BalanceDomain];
	/**
	 * Unique identifier for the withdrawal operation.
	 */
	withdrawal_id: string;
	/**
	 * The unique identifier of the asset to withdraw.
	 */
	asset_id: string;
	/**
	 * The amount of the asset to withdraw.
	 */
	amount: bigint;
}
/**
 * Outcome of a collateral withdrawal operation.
 */
export type WithdrawCollateralResult =
	| {
			/**
			 * Withdrawal was successfully planned or executed.
			 */
			Ok: null;
	  }
	| {
			/**
			 * Failed to process withdrawal.
			 */
			Err: WithdrawCollateralError;
	  };
export type WithdrawFundError =
	{ TransferFailed: string } | { InsufficientFunds: null } | { Common: CommonError };
export interface WithdrawFundParams {
	to: Principal;
	request_id: string;
	fund_type: FundType;
	asset_id: string;
	amount: bigint;
}
export type WithdrawFundResult = { Ok: bigint } | { Err: WithdrawFundError };
export interface _SERVICE {
	/**
	 * Accepts a position transfer from another clearing canister.
	 *
	 * This method validates the series and increases the target user's position based on the provided
	 * proof. This method is gated to canister controllers.
	 */
	accept_position_transfer: ActorMethod<[PositionProof], AcceptPositionTransferResult>;
	/**
	 * Aggregates, for a series, the long/short lean of a supplied set of
	 * principals, broken down per outcome.
	 *
	 * The clearing layer ascribes no meaning to the set — it is just a list of
	 * principals the caller passes in; how it is assembled is a concern of the
	 * consuming layer-2 / application, not of clearing.
	 *
	 * Returns **counts only**: per outcome, how many of the supplied principals
	 * are net long vs net short, plus the number of distinct principals with any
	 * non-flat position on the series. It never exposes individual identities,
	 * sides, quantities, or P&L, so no single principal's own side is ever singled
	 * out.
	 *
	 * The supplied set is de-duplicated and capped at `MAX_AGGREGATE_PRINCIPALS`.
	 * Guarded by `caller_is_not_anonymous`, matching the other position reads.
	 */
	aggregate_lean: ActorMethod<[AggregateLeanParams], AggregateLean>;
	/**
	 * Aggregates each supplied principal's settled-position win/total counts (and
	 * net realized `PnL`) over an arbitrary half-open window `[from_ts, to_ts)`.
	 *
	 * `win_count / settled_count` per entry is that principal's window accuracy —
	 * the same metric [`list_leaderboard`] exposes, but over a caller-chosen span
	 * rather than a fixed calendar bucket. A consumer scoring a cohort (e.g. one
	 * league side of a "battle") sums the entries it gets back for that side's
	 * members.
	 *
	 * Unlike [`list_leaderboard`], the arbitrary window cannot use the
	 * `(window, period)` index, so this scans the raw `EVENTS` log once —
	 * `O(events)`, the same cost class as [`get_trade_history`] and the
	 * post-upgrade leaderboard rebuild. Only `Settled` events count; a `Settled`
	 * event's `qty` is the position's signed `cashflow_usd`, so a win is
	 * `qty > 0`, matching the leaderboard's rule exactly. Pass `series_ids` to
	 * scope the count to a set of series (e.g. one market category); `None`
	 * counts every series. Guarded by `caller_is_not_anonymous`, matching the
	 * other settlement-derived reads.
	 *
	 * [`get_trade_history`]: crate::api::trade::get_trade_history
	 */
	aggregate_settlement_accuracy: ActorMethod<
		[AggregateSettlementAccuracyParams],
		Array<SettlementAccuracyEntry>
	>;
	/**
	 * One-shot, idempotent backfill of `Settled` events for plans finalized
	 * before per-user event emission was added to `apply_settlement_accounting_logic`.
	 *
	 * Iterates `SETTLEMENT_PLANS` in sorted order starting after
	 * `params.start_after`. For each `Finalised` plan it synthesizes one
	 * `EventType::Settled` event per `SettlementPosition` whose `(user,
	 * series_id)` pair has no pre-existing `Settled` event in `EVENTS`. The
	 * synthesized event's `timestamp` is the plan's original
	 * `idempotency_ns` so backfilled rows sort alongside the live events
	 * that would have been written at settlement time.
	 *
	 * Yields cooperatively when the instruction counter is high so a single
	 * call cannot exhaust the update budget. Callers loop until the response
	 * returns `next_cursor: None`.
	 */
	backfill_settlement_events: ActorMethod<
		[BackfillSettlementEventsParams],
		BackfillSettlementEventsResult
	>;
	/**
	 * Cancels a stuck fund withdrawal and refunds the internal ledger balance.
	 *
	 * This method is gated to canister controllers.
	 */
	cancel_fund_withdrawal: ActorMethod<[CancelFundWithdrawalParams], CancelFundWithdrawalResult>;
	/**
	 * Cancels an existing limit order and releases the reserved collateral.
	 *
	 * Only the creator of the order can cancel it.
	 */
	cancel_limit_order: ActorMethod<[CancelLimitOrderParams], SubmitMatchedTradeResult>;
	/**
	 * Returns the current global configuration of the Clearing canister.
	 */
	config: ActorMethod<[], Config>;
	/**
	 * Deposits collateral into the user's account state.
	 *
	 * This is a multi-phase operation:
	 * 1. Building a [`DepositPlan`] for idempotency.
	 * 2. Executing the asynchronous ledger transfer (`transfer_from`).
	 * 3. Finalising the internal collateral balances.
	 */
	deposit_collateral: ActorMethod<[DepositCollateralParams], DepositCollateralResult>;
	/**
	 * Freezes a user's position to prepare it for transfer to another clearing canister.
	 *
	 * Once frozen, the position is removed from active state and a [`PositionProof`] is issued.
	 * This method is gated to canister controllers.
	 */
	freeze_position_for_transfer: ActorMethod<
		[FreezePositionForTransferParams],
		[] | [PositionProof]
	>;
	/**
	 * Retrieves the current user's account state, optionally refreshing balances.
	 *
	 * # Arguments
	 * * `params` - Includes an optional `refresh` flag to trigger external ledger checks.
	 */
	get_account_state: ActorMethod<[GetAccountStateParams], GetAccountStateResult>;
	/**
	 * Retrieves the current user's account state (query only).
	 *
	 * This does not refresh balances from external ledgers.
	 */
	get_account_state_query: ActorMethod<[], GetAccountStateResult>;
	/**
	 * Returns the current domain policies for all configured domains.
	 *
	 * This method is gated to canister controllers.
	 */
	get_domain_policies: ActorMethod<[], Array<[BalanceDomain, DomainPolicy]>>;
	/**
	 * Returns the current balances of the Insurance Fund and Treasury.
	 *
	 * This method is gated to canister controllers.
	 */
	get_funds: ActorMethod<[], GetFundsResult>;
	/**
	 * Retrieves all active limit orders for the caller.
	 */
	get_orders: ActorMethod<[], Array<LimitOrder>>;
	/**
	 * Retrieves a specific position for the caller.
	 */
	get_position: ActorMethod<[GetPositionParams], [] | [Position]>;
	/**
	 * Retrieves all open positions for the caller.
	 */
	get_positions: ActorMethod<[], Array<Position>>;
	/**
	 * Returns the principal of the Series Registry canister.
	 */
	get_registry_canister: ActorMethod<[], Principal>;
	/**
	 * Returns a single series' executed trades aggregated into fixed-width
	 * [`PriceHistoryInterval`] candles (open/high/low/close + volume + trade
	 * count), time-ordered, so a front end can render a time-scoped consensus/price
	 * chart without fetching and re-bucketing the raw per-trade tape that
	 * [`list_series_trade_history`] returns.
	 *
	 * `start_time`/`end_time` window the trades considered (inclusive lower,
	 * exclusive upper), letting the caller request just the window it draws; the
	 * `interval` selects hourly or daily resolution. Buckets with no trades are
	 * omitted — a young or untraded market returns an empty history rather than
	 * fabricated points — and the result is capped at [`MAX_PRICE_HISTORY_POINTS`]
	 * most-recent candles.
	 *
	 * Served from the same `SERIES_TRADE_HISTORY` index as
	 * [`list_series_trade_history`], so it adds no write-path cost and no persisted
	 * state. Aggregation scans newest-first and stops once it has filled
	 * [`MAX_PRICE_HISTORY_POINTS`] buckets, so both the work and the payload are
	 * bounded even when `start_time`/`end_time` are open-ended (see
	 * [`aggregate_price_history`]). Guarded by `caller_is_not_anonymous`, matching
	 * the other series-scoped reads.
	 */
	get_series_price_history: ActorMethod<[GetSeriesPriceHistoryParams], SeriesPriceHistory>;
	/**
	 * Returns the full settlement plan including per-position accounting details (admin only).
	 */
	get_settlement_plan: ActorMethod<[string], [] | [SettlementPlan]>;
	/**
	 * Returns the public settlement progress for a derivative series without exposing user positions.
	 */
	get_settlement_status: ActorMethod<[string], [] | [SettlementStatusView]>;
	/**
	 * Retrieves the trade history for the caller. Returns events that move the
	 * user's economic position — executed trades, settlements, and liquidations.
	 * Order-placement events are excluded so the response is bounded to events
	 * that materially settle cashflow.
	 *
	 * Results are sorted by `(timestamp, event_id)` so that backfilled rows whose
	 * timestamp reflects the original settlement time interleave chronologically
	 * with live events rather than appearing in storage-insertion order.
	 */
	get_trade_history: ActorMethod<[], Array<Event>>;
	/**
	 * Returns the official number of decimals for USD accounting.
	 */
	get_usd_decimals: ActorMethod<[], number>;
	/**
	 * Handles incoming HTTP requests for Prometheus metrics.
	 *
	 * This endpoint is restricted to canister controllers and serves metrics at `/metrics`.
	 */
	http_request: ActorMethod<[HttpRequest], HttpResponse>;
	/**
	 * Returns a list of all supported collateral assets with their metrics.
	 */
	list_collateral_assets: ActorMethod<[], Array<CollateralAssetInfo>>;
	/**
	 * Returns ranked standings for a calendar window (this week / this month / all
	 * time), derived from settled-position `PnL`, with each entry's prior-window
	 * rank for ↑/↓ deltas and stable cursor pagination.
	 *
	 * Principals are ranked by net realized `PnL` (the signed sum of their
	 * settlement cashflows in the window) descending, using competition ranking
	 * (ties share a rank). Pass `members` to rank within a league / affiliation
	 * member set instead of the whole population — that set is ranked in
	 * isolation and every listed member is included even with no settlements in
	 * the window, so the front end can read a user's rank within their league.
	 *
	 * Served from the `SETTLEMENT_LEADERBOARD` index, so a call ranks only the two
	 * relevant period buckets (current + prior) rather than scanning the whole
	 * event log. Guarded by `caller_is_not_anonymous`, matching the other
	 * settlement-derived reads.
	 */
	list_leaderboard: ActorMethod<[ListLeaderboardParams], LeaderboardPage>;
	/**
	 * Returns a list of all active limit orders, potentially filtered by series.
	 */
	list_orders: ActorMethod<[ListOrdersParams], Array<LimitOrder>>;
	/**
	 * Returns a list of all derivative series currently cached in the clearing canister.
	 */
	list_series: ActorMethod<[], Array<Series>>;
	/**
	 * Returns each requested series' settlement status in one call — the batch form
	 * of [`get_settlement_status`].
	 *
	 * A resolution solver checks "is this market already settled?" for every due
	 * market on each pass; done one id at a time that is N sequential canister
	 * calls. This collapses them into one: each id is looked up in
	 * `SETTLEMENT_PLANS` and returned with its [`SettlementStatusView`], or `None`
	 * when no plan exists yet (the series is still open / not being settled).
	 * Results are one per requested id, in request order, so the caller can zip them
	 * back against its input; the `series_id` is echoed on each entry so a `None`
	 * status is still attributable.
	 *
	 * The work is `O(#series_ids)` map lookups — bounded by the request, not by the
	 * number of plans — so callers should pass the (already bounded) set they care
	 * about, e.g. the registry's "due" candidates. Reads the same
	 * `SETTLEMENT_PLANS` map as [`get_settlement_status`] and mirrors the
	 * aggregate-read shape of
	 * [`list_series_traded_volumes`](crate::api::trade::list_series_traded_volumes).
	 * Guarded by `caller_is_not_anonymous`, matching the other settlement reads.
	 */
	list_series_settlement_statuses: ActorMethod<
		[ListSeriesSettlementStatusesParams],
		Array<SeriesSettlementStatus>
	>;
	/**
	 * Returns the executed-trade history for a single series, with stable cursor
	 * pagination.
	 *
	 * Unlike [`get_trade_history`] — which is caller-scoped — this surfaces every
	 * participant's executed trades on `series_id`, so a front end can derive a
	 * market-wide price history (e.g. a YES-probability sparkline) from the
	 * per-trade `price`/`timestamp` rather than only the viewer's own fills.
	 *
	 * Each trade is returned as a single [`SeriesTradePoint`] (the two
	 * counterparty rows are collapsed), ordered by `event_id` ascending — i.e.
	 * execution order. Served from the `SERIES_TRADE_HISTORY` index, so the read
	 * is `O(log series + page)` rather than a scan of the whole event log. The
	 * cursor is the last trade's `event_id` and is exclusive; since executed-trade
	 * `event_id`s are strictly increasing, resuming neither drops nor repeats a
	 * trade. Mirrors the pagination contract of `list_settled_series`.
	 */
	list_series_trade_history: ActorMethod<[ListSeriesTradeHistoryParams], SeriesTradeHistoryPage>;
	/**
	 * Returns each requested series' cumulative market-wide traded volume — the
	 * notional that changed hands (sum of `qty · price`) in USD base units — plus
	 * its executed-trade count, one entry per requested id in request order.
	 *
	 * Lets a front end label a page of market cards in a single call instead of a
	 * per-card read. An unknown or untraded series totals zero. Reads the
	 * `SERIES_TRADED_VOLUME` aggregate that [`index_executed_trade`] maintains
	 * alongside the trade index, so the work is `O(#series_ids)` lookups — bounded
	 * regardless of how many trades a series has accumulated, rather than scanning
	 * each series' tape. Guarded by `caller_is_not_anonymous`, matching the other
	 * series-scoped reads.
	 *
	 * [`index_executed_trade`]: crate::memory::index_executed_trade
	 */
	list_series_traded_volumes: ActorMethod<
		[ListSeriesTradedVolumesParams],
		Array<SeriesTradedVolume>
	>;
	/**
	 * Lists the ids of series that have been settled (resolved), with stable
	 * cursor pagination.
	 *
	 * A series appears here as soon as a [`SettlementPlan`] is opened for it — in
	 * any [`PlanStatus`] — which is precisely when it stops being tradeable. This
	 * is the authoritative resolution set: the clearing canister owns settlement
	 * state, the registry does not. Front ends that build a "currently-tradeable"
	 * candidate set call the registry's `list_series_with` with `only_unexpired`
	 * for the open/unexpired catalog and subtract the ids returned here to drop the
	 * resolved markets, instead of reconstructing resolution from the activity log.
	 *
	 * Ids are returned in ascending order from `SETTLEMENT_PLANS` (a `BTreeMap`
	 * keyed by `SeriesId`), so paging with the previous response's `next_cursor`
	 * is stable as long as the underlying set is not mutated mid-traversal.
	 */
	list_settled_series: ActorMethod<[ListSettledSeriesParams], SettledSeriesPage>;
	/**
	 * Exports internal state as Prometheus metrics.
	 *
	 * This method is gated to canister controllers.
	 */
	metrics: ActorMethod<[], string>;
	/**
	 * Migrates a user's entire domain state (balances, cash, margin, positions, orders)
	 * from one balance domain to another.
	 *
	 * This operation is idempotent: providing the same `migration_id` returns `Ok`
	 * if the migration was already finalised.
	 *
	 * Pre-conditions enforced:
	 * - `from_domain != to_domain`
	 * - No in-flight deposit, withdrawal, or settlement plans for the user in the source domain.
	 * - User must have state to migrate.
	 */
	migrate_domain: ActorMethod<[MigrateDomainParams], MigrateDomainResult>;
	/**
	 * Mints a complete set of categorical outcome positions.
	 *
	 * Returns 1 unit of every outcome position in the series in exchange for the
	 * full collateral requirement (1.0 USD vUSD).
	 */
	mint_complete_set: ActorMethod<[string, bigint], SubmitMatchedTradeResult>;
	/**
	 * Redeems a complete set of categorical outcome positions for collateral.
	 *
	 * Returns 1.0 USD (vUSD) for every full set of N outcome positions provided.
	 */
	redeem_complete_set: ActorMethod<[string, bigint], SubmitMatchedTradeResult>;
	/**
	 * Refreshes the metadata (decimals, fee, symbol) of an already registered ICRC asset.
	 *
	 * This method is gated to canister controllers.
	 */
	refresh_icrc_asset_metadata: ActorMethod<
		[RefreshIcrcAssetMetadataParams],
		RefreshIcrcAssetMetadataResult
	>;
	/**
	 * Automatically registers an ICRC asset by fetching its metadata from the ledger.
	 *
	 * This method is gated to canister controllers.
	 */
	register_icrc_asset: ActorMethod<[RegisterIcrcAssetParams], RegisterIcrcAssetResult>;
	/**
	 * Admin function to manually resume a stuck settlement plan, e.g., if the timer was dropped during
	 * upgrade.
	 */
	resume_settlement: ActorMethod<[string], SettleSeriesResult>;
	/**
	 * Sets the principal of the Series Registry canister.
	 *
	 * This principal is used to discover and validate derivative series.
	 * This method is gated to canister controllers.
	 */
	set_registry_canister: ActorMethod<[Principal], undefined>;
	/**
	 * Settles a derivative series at a specific price.
	 *
	 * This is a background operation consisting of:
	 * 1. Creating or resuming a [`SettlementPlan`].
	 * 2. Updating internal USD cash balances for all participants based on payoffs.
	 * 3. Releasing margin requirements for the settled positions.
	 * 4. Finalising the plan and removing the series data.
	 *
	 * **Note on Chunking:** To avoid instruction limits, this method processes positions in batches
	 * of 100 per call. If there are many positions, the method will return
	 * [`SettleSeriesResult::Processing`]. The caller must repeatedly call `settle_series` with the
	 * same parameters until it returns [`SettleSeriesResult::Ok`].
	 *
	 * **Authorization:** Every call is gated to canister controllers or the designated oracle for
	 * the series. Unauthorized callers are rejected even if a plan already exists.
	 */
	settle_series: ActorMethod<[SettleSeriesParams], SettleSeriesResult>;
	/**
	 * Exports internal state as a structured `Stats` object.
	 *
	 * This method is gated to canister controllers.
	 */
	stats: ActorMethod<[], Stats>;
	/**
	 * Submits a limit order for the caller.
	 *
	 * This atomically blocks the required collateral for the order.
	 */
	submit_limit_order: ActorMethod<[SubmitLimitOrderParams], SubmitMatchedTradeResult>;
	/**
	 * Submits a market order to match an existing limit order.
	 *
	 * The caller is the taker. An optional `qty` caps the fill: the trade executes for
	 * `min(qty, resting order qty)` at the order's price and the unfilled remainder stays
	 * on the book with proportionally reduced blocked margin. `None` fills the entire
	 * resting order.
	 */
	submit_market_order: ActorMethod<[SubmitMarketOrderParams], SubmitMatchedTradeResult>;
	/**
	 * Submits a matched trade from an exchange for clearing.
	 *
	 * NOTE: Access is currently restricted to authorized exchange intermediaries
	 * (represented by canister controllers in this version).
	 */
	submit_matched_trade: ActorMethod<[SubmitMatchedTradeParams], SubmitMatchedTradeResult>;
	/**
	 * Adds or updates dynamic metrics for a collateral asset.
	 *
	 * This method is gated to canister controllers.
	 */
	update_asset_metrics: ActorMethod<[UpdateAssetMetricsParams], undefined>;
	/**
	 * Updates the price of an asset.
	 *
	 * This method can be called by canister controllers or authorized oracles.
	 */
	update_asset_price: ActorMethod<[UpdateAssetPriceParams], UpdateAssetPriceResult>;
	/**
	 * Updates which balance domains may hold this collateral asset (deposits and withdrawals).
	 *
	 * This method is gated to canister controllers.
	 */
	update_collateral_allowed_domains: ActorMethod<
		[UpdateCollateralAllowedDomainsParams],
		UpdateCollateralAllowedDomainsResult
	>;
	/**
	 * Adds or updates a collateral asset configuration.
	 *
	 * This method is gated to canister controllers.
	 */
	update_collateral_asset: ActorMethod<[UpdateCollateralAssetParams], undefined>;
	/**
	 * Updates the global configuration for the Clearing canister.
	 *
	 * Immutable properties like `internal_ledger_id` and `version` are preserved from the existing
	 * state. This method is gated to canister controllers.
	 */
	update_config: ActorMethod<[Config], undefined>;
	/**
	 * Adds or updates the policy for a specific balance domain.
	 *
	 * This method is gated to canister controllers.
	 */
	update_domain_policy: ActorMethod<[UpdateDomainPolicyParams], undefined>;
	/**
	 * Withdraws collateral from the user's account state to an external address.
	 *
	 * This implements the "Deterministic Withdrawal Policy":
	 * 1. Calculate current account equity in USD.
	 * 2. Verify equity >= `reserved_margin_usd` (risk check).
	 * 3. If ok, proceed with asynchronous ledger transfer.
	 */
	withdraw_collateral: ActorMethod<[WithdrawCollateralParams], WithdrawCollateralResult>;
	/**
	 * Withdraws assets from the Insurance Fund or Treasury to an external wallet.
	 *
	 * This method is gated to canister controllers.
	 */
	withdraw_fund: ActorMethod<[WithdrawFundParams], WithdrawFundResult>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
