/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const ErcToken = IDL.Record({
		decimals: IDL.Nat8,
		token_address: IDL.Text,
		chain_id: IDL.Nat64
	});
	const NativeEvmAsset = IDL.Record({
		decimals: IDL.Nat8,
		chain_id: IDL.Nat64
	});
	const Asset = IDL.Variant({
		Erc20: ErcToken,
		Icrc: IDL.Principal,
		NativeEvm: NativeEvmAsset
	});
	const BalanceDomain = IDL.Variant({
		ViciXp: IDL.Null,
		Social: IDL.Null,
		Playground: IDL.Null,
		Settlement: IDL.Null
	});
	const CollateralAssetConfig = IDL.Record({
		decimals: IDL.Nat8,
		asset: Asset,
		is_enabled: IDL.Bool,
		allowed_balance_domains: IDL.Vec(BalanceDomain),
		oracle_id: IDL.Opt(IDL.Text),
		asset_id: IDL.Text,
		symbol: IDL.Text
	});
	const Config = IDL.Record({
		insurance_fund_fee_ratio: IDL.Nat16,
		internal_ledger: CollateralAssetConfig,
		signer_canister: IDL.Principal,
		version: IDL.Nat32,
		evm_rpc: IDL.Principal,
		protocol_fee_ratio: IDL.Nat16
	});
	const DecimalValue = IDL.Record({ decimals: IDL.Nat8, value: IDL.Nat });
	const Price = IDL.Record({
		timestamp: IDL.Opt(IDL.Nat64),
		oracle_id: IDL.Opt(IDL.Text),
		decimal: DecimalValue
	});
	const PositionProof = IDL.Record({
		qty: IDL.Int,
		signature: IDL.Vec(IDL.Nat8),
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		user: IDL.Principal,
		transfer_id: IDL.Text,
		valuation_price: IDL.Opt(Price),
		clearing_id: IDL.Principal
	});
	const CommonError = IDL.Variant({
		Internal: IDL.Text,
		InvalidInput: IDL.Text,
		MathOverflow: IDL.Null,
		Unauthorized: IDL.Null,
		RegistryNotSet: IDL.Null
	});
	const TradeError = IDL.Variant({
		SelfTradingNotAllowed: IDL.Null,
		OrderNotFound: IDL.Text,
		SeriesNotStarted: IDL.Record({
			start_ns: IDL.Nat64,
			series_id: IDL.Text
		}),
		ArbitrageLimitExceeded: IDL.Record({
			limit_usd: IDL.Nat,
			sum_usd: IDL.Nat
		}),
		RegistryError: IDL.Text,
		SeriesExpired: IDL.Record({
			expiry_ns: IDL.Nat64,
			series_id: IDL.Text
		}),
		InsufficientMargin: IDL.Record({
			balance: IDL.Nat,
			user: IDL.Principal,
			required: IDL.Nat
		}),
		NotOrderCreator: IDL.Null,
		SeriesNotFound: IDL.Text,
		SeriesAlreadySettled: IDL.Text,
		NotAuthorizedToTrade: IDL.Null,
		Common: CommonError
	});
	const AcceptPositionTransferResult = IDL.Variant({
		Ok: IDL.Bool,
		Err: TradeError
	});
	const AggregateLeanParams = IDL.Record({
		series_id: IDL.Text,
		principals: IDL.Vec(IDL.Principal)
	});
	const OutcomeLean = IDL.Record({
		total: IDL.Nat64,
		outcome_id: IDL.Opt(IDL.Text),
		long: IDL.Nat64,
		short: IDL.Nat64
	});
	const AggregateLean = IDL.Record({
		total: IDL.Nat64,
		series_id: IDL.Text,
		outcomes: IDL.Vec(OutcomeLean)
	});
	const AggregateSettlementAccuracyParams = IDL.Record({
		to_ts: IDL.Opt(IDL.Nat64),
		members: IDL.Vec(IDL.Principal),
		from_ts: IDL.Opt(IDL.Nat64),
		series_ids: IDL.Opt(IDL.Vec(IDL.Text))
	});
	const SettlementAccuracyEntry = IDL.Record({
		principal: IDL.Principal,
		realized_pnl: IDL.Int,
		win_count: IDL.Nat64,
		settled_count: IDL.Nat64
	});
	const BackfillSettlementEventsParams = IDL.Record({
		start_after: IDL.Opt(IDL.Text)
	});
	const BackfillSettlementEventsResult = IDL.Record({
		plans_scanned: IDL.Nat64,
		events_emitted: IDL.Nat64,
		events_skipped: IDL.Nat64,
		next_cursor: IDL.Opt(IDL.Text)
	});
	const CancelFundWithdrawalParams = IDL.Record({ request_id: IDL.Text });
	const CancelFundWithdrawalError = IDL.Variant({
		PlanNotFound: IDL.Null,
		InvalidPlanStatus: IDL.Null,
		Common: CommonError
	});
	const CancelFundWithdrawalResult = IDL.Variant({
		Ok: IDL.Null,
		Err: CancelFundWithdrawalError
	});
	const CancelLimitOrderParams = IDL.Record({ order_id: IDL.Text });
	const SubmitMatchedTradeResult = IDL.Variant({
		Ok: IDL.Bool,
		Err: TradeError
	});
	const DepositCollateralParams = IDL.Record({
		deposit_id: IDL.Text,
		domain: IDL.Opt(BalanceDomain),
		asset_id: IDL.Text,
		amount: IDL.Nat
	});
	const AssetError = IDL.Variant({
		TransferError: IDL.Text,
		InsufficientBalance: IDL.Record({
			balance: IDL.Nat,
			required: IDL.Nat
		}),
		MathOverflow: IDL.Null,
		InvalidAssetId: IDL.Text,
		CallError: IDL.Record({
			method: IDL.Text,
			code: IDL.Int32,
			message: IDL.Text
		}),
		InvalidAssetForHandler: IDL.Null,
		UnsupportedAsset: IDL.Null
	});
	const DepositCollateralError = IDL.Variant({
		DomainNotAllowed: IDL.Record({
			domain: BalanceDomain,
			asset_id: IDL.Text
		}),
		MathOverflow: IDL.Null,
		Asset: AssetError
	});
	const DepositCollateralResult = IDL.Variant({
		Ok: IDL.Null,
		Err: DepositCollateralError
	});
	const FreezePositionForTransferParams = IDL.Record({
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		user: IDL.Principal,
		transfer_id: IDL.Text,
		valuation_price: IDL.Opt(Price)
	});
	const GetAccountStateParams = IDL.Record({
		domain: IDL.Opt(BalanceDomain),
		refresh: IDL.Opt(IDL.Bool)
	});
	const AssetWorth = IDL.Record({
		pre_haircut_value_usd: IDL.Nat,
		haircut_bps: IDL.Nat16,
		balance: IDL.Nat,
		value_usd: IDL.Nat,
		asset_id: IDL.Text
	});
	const AccountState = IDL.Record({
		user: IDL.Principal,
		reserved_margins_usd: IDL.Vec(IDL.Tuple(BalanceDomain, IDL.Nat)),
		cash_balances_usd: IDL.Vec(IDL.Tuple(BalanceDomain, IDL.Int)),
		balances: IDL.Vec(IDL.Tuple(BalanceDomain, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))))
	});
	const AccountStateResponse = IDL.Record({
		assets: IDL.Vec(AssetWorth),
		state: AccountState,
		total_equity_usd: IDL.Nat,
		available_margin_usd: IDL.Int
	});
	const AccountStateError = IDL.Variant({
		MathOverflow: IDL.Null,
		Asset: AssetError,
		NoAccountStateFound: IDL.Null
	});
	const GetAccountStateResult = IDL.Variant({
		Ok: AccountStateResponse,
		Err: AccountStateError
	});
	const DomainPolicy = IDL.Record({
		deposits_enabled: IDL.Bool,
		protocol_fee_ratio_override: IDL.Opt(IDL.Nat16),
		label: IDL.Text,
		withdrawals_enabled: IDL.Bool,
		insurance_fund_fee_ratio_override: IDL.Opt(IDL.Nat16)
	});
	const GetFundsResult = IDL.Record({
		insurance_fund: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
		treasury: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))
	});
	const Side = IDL.Variant({ Buy: IDL.Null, Sell: IDL.Null });
	const LimitOrder = IDL.Record({
		qty: IDL.Int,
		creator: IDL.Principal,
		outcome_id: IDL.Opt(IDL.Text),
		blocked_margin_usd: IDL.Nat,
		series_id: IDL.Text,
		side: Side,
		order_id: IDL.Text,
		price: Price,
		balance_domain: BalanceDomain
	});
	const GetPositionParams = IDL.Record({
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text
	});
	const Position = IDL.Record({
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		net_qty: IDL.Int,
		user: IDL.Principal,
		reserved_margin_usd: IDL.Nat
	});
	const PriceHistoryInterval = IDL.Variant({
		Day: IDL.Null,
		Hour: IDL.Null
	});
	const GetSeriesPriceHistoryParams = IDL.Record({
		interval: PriceHistoryInterval,
		series_id: IDL.Text,
		end_time: IDL.Opt(IDL.Nat64),
		start_time: IDL.Opt(IDL.Nat64)
	});
	const SeriesPriceCandle = IDL.Record({
		low: Price,
		high: Price,
		close: Price,
		open: Price,
		volume: IDL.Int,
		trade_count: IDL.Nat64,
		bucket_start_ns: IDL.Nat64
	});
	const SeriesPriceHistory = IDL.Record({
		candles: IDL.Vec(SeriesPriceCandle)
	});
	const PlanStatus = IDL.Variant({
		Finalised: IDL.Null,
		Planned: IDL.Null,
		Executing: IDL.Null
	});
	const PaymentIdempotency = IDL.Variant({ IcrcCreatedAtTimeNs: IDL.Nat64 });
	const SettlementPosition = IDL.Record({
		outcome_id: IDL.Opt(IDL.Text),
		net_qty: IDL.Int,
		user: IDL.Principal,
		reserved_margin_usd: IDL.Nat,
		cashflow_usd: IDL.Int
	});
	const SettlementInput = IDL.Variant({
		Price: Price,
		Outcome: IDL.Text
	});
	const SettlementPlan = IDL.Record({
		status: PlanStatus,
		idempotency_ns: PaymentIdempotency,
		series_id: IDL.Text,
		fee_usd: IDL.Nat,
		accounting_cursor: IDL.Nat64,
		insurance_fee_usd: IDL.Nat,
		positions: IDL.Vec(SettlementPosition),
		accounting_applied: IDL.Bool,
		balance_domain: BalanceDomain,
		oracle_source: IDL.Text,
		settlement: SettlementInput
	});
	const SettlementStatusView = IDL.Record({
		status: PlanStatus,
		series_id: IDL.Text,
		fee_usd: IDL.Nat,
		accounting_cursor: IDL.Nat64,
		insurance_fee_usd: IDL.Nat,
		accounting_applied: IDL.Bool,
		balance_domain: BalanceDomain,
		oracle_source: IDL.Text,
		total_positions: IDL.Nat64,
		settlement: SettlementInput
	});
	const EventType = IDL.Variant({
		OrderPlaced: IDL.Null,
		Executed: IDL.Null,
		Liquidated: IDL.Null,
		Settled: IDL.Null
	});
	const Event = IDL.Record({
		qty: IDL.Int,
		series_id: IDL.Text,
		user: IDL.Principal,
		timestamp: IDL.Nat64,
		event_id: IDL.Nat64,
		price: Price,
		event_type: EventType,
		clearing_id: IDL.Principal
	});
	const HttpRequest = IDL.Record({
		url: IDL.Text,
		method: IDL.Text,
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))
	});
	const HttpResponse = IDL.Record({
		body: IDL.Vec(IDL.Nat8),
		headers: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
		status_code: IDL.Nat16
	});
	const AssetMetrics = IDL.Record({
		haircut_bps: IDL.Nat16,
		latest_transfer_fee: IDL.Opt(IDL.Nat),
		insurance_fee_ratio: IDL.Opt(IDL.Nat16),
		last_updated_ns: IDL.Opt(IDL.Nat64),
		protocol_fee_ratio: IDL.Opt(IDL.Nat16),
		price_usd: DecimalValue
	});
	const CollateralAssetInfo = IDL.Record({
		metrics: IDL.Opt(AssetMetrics),
		config: CollateralAssetConfig
	});
	const LeaderboardWindow = IDL.Variant({
		AllTime: IDL.Null,
		Week: IDL.Null,
		Month: IDL.Null
	});
	const ListLeaderboardParams = IDL.Record({
		members: IDL.Opt(IDL.Vec(IDL.Principal)),
		window: LeaderboardWindow,
		start_after: IDL.Opt(IDL.Nat64),
		limit: IDL.Opt(IDL.Nat64)
	});
	const LeaderboardEntry = IDL.Record({
		principal: IDL.Principal,
		prior_rank: IDL.Opt(IDL.Nat64),
		rank: IDL.Nat64,
		realized_pnl: IDL.Int,
		win_count: IDL.Nat64,
		settled_count: IDL.Nat64
	});
	const LeaderboardPage = IDL.Record({
		total: IDL.Nat64,
		next_cursor: IDL.Opt(IDL.Nat64),
		items: IDL.Vec(LeaderboardEntry)
	});
	const ListOrdersParams = IDL.Record({ series_id: IDL.Opt(IDL.Text) });
	const PayoffType = IDL.Variant({
		Put: IDL.Null,
		Binary: IDL.Null,
		Call: IDL.Null,
		Categorical: IDL.Null
	});
	const FiatUnit = IDL.Variant({
		Chf: IDL.Null,
		Eur: IDL.Null,
		Gbp: IDL.Null,
		Usd: IDL.Null
	});
	const SocialReward = IDL.Record({
		title: IDL.Text,
		description: IDL.Opt(IDL.Text),
		icon_url: IDL.Opt(IDL.Text)
	});
	const NonMonetaryUnit = IDL.Variant({
		Points: IDL.Null,
		Social: SocialReward
	});
	const PayoutUnit = IDL.Variant({
		Fiat: FiatUnit,
		Asset: Asset,
		NonMonetary: NonMonetaryUnit
	});
	const Description = IDL.Record({
		html: IDL.Opt(IDL.Text),
		markdown: IDL.Opt(IDL.Text),
		plain: IDL.Text
	});
	const Resolution = IDL.Record({ clause: IDL.Text });
	const Outcome = IDL.Record({
		id: IDL.Text,
		title: IDL.Text,
		description: IDL.Opt(Description),
		icon_url: IDL.Opt(IDL.Text)
	});
	const TradingAccess = IDL.Variant({
		Open: IDL.Null,
		Restricted: IDL.Record({ groups: IDL.Vec(IDL.Text) })
	});
	const Series = IDL.Record({
		title: IDL.Text,
		strike: IDL.Opt(Price),
		creator: IDL.Principal,
		payoff_type: PayoffType,
		engine_id: IDL.Opt(IDL.Text),
		payout_unit: PayoutUnit,
		expiry_ns: IDL.Nat64,
		banner_url: IDL.Opt(IDL.Text),
		start_ns: IDL.Opt(IDL.Nat64),
		series_id: IDL.Text,
		underlying: IDL.Text,
		locale: IDL.Opt(IDL.Text),
		description: Description,
		resolution: Resolution,
		outcomes: IDL.Opt(IDL.Vec(Outcome)),
		created_at_ns: IDL.Nat64,
		icon_url: IDL.Opt(IDL.Text),
		trading_access: IDL.Vec(TradingAccess),
		price_precision: IDL.Nat8,
		balance_domain: BalanceDomain,
		oracle_source: IDL.Text,
		forked_from: IDL.Opt(IDL.Text)
	});
	const ListSeriesSettlementStatusesParams = IDL.Record({
		series_ids: IDL.Vec(IDL.Text)
	});
	const SeriesSettlementStatus = IDL.Record({
		status: IDL.Opt(SettlementStatusView),
		series_id: IDL.Text
	});
	const ListSeriesTradeHistoryParams = IDL.Record({
		series_id: IDL.Text,
		start_after: IDL.Opt(IDL.Nat64),
		limit: IDL.Opt(IDL.Nat64)
	});
	const SeriesTradePoint = IDL.Record({
		qty: IDL.Int,
		timestamp: IDL.Nat64,
		event_id: IDL.Nat64,
		price: Price
	});
	const SeriesTradeHistoryPage = IDL.Record({
		next_cursor: IDL.Opt(IDL.Nat64),
		items: IDL.Vec(SeriesTradePoint)
	});
	const ListSeriesTradedVolumesParams = IDL.Record({
		series_ids: IDL.Vec(IDL.Text)
	});
	const SeriesTradedVolume = IDL.Record({
		series_id: IDL.Text,
		volume: IDL.Int,
		trade_count: IDL.Nat64
	});
	const ListSettledSeriesParams = IDL.Record({
		start_after: IDL.Opt(IDL.Text),
		limit: IDL.Opt(IDL.Nat64),
		balance_domain: IDL.Opt(BalanceDomain)
	});
	const SettledSeriesPage = IDL.Record({
		next_cursor: IDL.Opt(IDL.Text),
		items: IDL.Vec(IDL.Text)
	});
	const MigrateDomainParams = IDL.Record({
		from_domain: BalanceDomain,
		migration_id: IDL.Text,
		to_domain: BalanceDomain
	});
	const MigrationError = IDL.Variant({
		NoStateTOMigrate: IDL.Null,
		SameDomain: IDL.Null,
		InFlightPlansExist: IDL.Null,
		Common: CommonError
	});
	const MigrateDomainResult = IDL.Variant({
		Ok: IDL.Null,
		Err: MigrationError
	});
	const RefreshIcrcAssetMetadataParams = IDL.Record({ asset_id: IDL.Text });
	const RefreshIcrcAssetMetadataError = IDL.Variant({
		AssetNotFound: IDL.Null,
		NotAnIcrcAsset: IDL.Null,
		Common: CommonError
	});
	const RefreshIcrcAssetMetadataResult = IDL.Variant({
		Ok: IDL.Null,
		Err: RefreshIcrcAssetMetadataError
	});
	const RegisterIcrcAssetParams = IDL.Record({
		haircut_bps: IDL.Nat16,
		is_enabled: IDL.Bool,
		allowed_balance_domains: IDL.Vec(BalanceDomain),
		ledger_id: IDL.Principal,
		oracle_id: IDL.Opt(IDL.Text),
		asset_id: IDL.Text
	});
	const RegisterIcrcAssetError = IDL.Variant({
		InvalidAllowedBalanceDomains: IDL.Null,
		AssetAlreadyExists: IDL.Null,
		VusdCannotBeCollateral: IDL.Null,
		Common: CommonError
	});
	const RegisterIcrcAssetResult = IDL.Variant({
		Ok: IDL.Null,
		Err: RegisterIcrcAssetError
	});
	const SettlementError = IDL.Variant({
		InconsistentSettlement: IDL.Record({
			requested: SettlementInput,
			existing: SettlementInput
		}),
		MathOverflow: IDL.Null,
		SolvencyViolation: IDL.Record({
			total_net_payoff: IDL.Nat,
			total_collateral_usd: IDL.Nat
		}),
		Asset: AssetError,
		Common: CommonError
	});
	const SettleSeriesResult = IDL.Variant({
		Ok: IDL.Null,
		Err: SettlementError,
		Processing: IDL.Null
	});
	const SettleSeriesParams = IDL.Record({
		series_id: IDL.Text,
		settlement: SettlementInput
	});
	const Stats = IDL.Record({
		total_users: IDL.Nat64,
		margin_balances: IDL.Vec(IDL.Tuple(Asset, IDL.Nat)),
		total_collateral_locked: IDL.Nat,
		total_trades: IDL.Nat64,
		total_series: IDL.Nat64,
		open_interest: IDL.Nat,
		event_counts: IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat64))
	});
	const SubmitLimitOrderParams = IDL.Record({
		qty: IDL.Int,
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		side: Side,
		order_id: IDL.Text,
		price: Price
	});
	const SubmitMarketOrderParams = IDL.Record({
		qty: IDL.Opt(IDL.Int),
		trade_id: IDL.Text,
		matching_order_id: IDL.Text
	});
	const SubmitMatchedTradeParams = IDL.Record({
		qty: IDL.Int,
		trade_id: IDL.Text,
		outcome_id: IDL.Opt(IDL.Text),
		series_id: IDL.Text,
		seller: IDL.Principal,
		buyer_unblock_amount: IDL.Opt(IDL.Nat),
		buyer: IDL.Principal,
		price: Price,
		seller_unblock_amount: IDL.Opt(IDL.Nat)
	});
	const UpdateAssetMetricsParams = IDL.Record({
		metrics: AssetMetrics,
		asset_id: IDL.Text
	});
	const UpdateAssetPriceParams = IDL.Record({
		price: Price,
		asset_id: IDL.Text
	});
	const UpdateAssetPriceError = IDL.Variant({
		AssetNotFound: IDL.Null,
		AssetMetricsNotInitialized: IDL.Null,
		OracleNotConfigured: IDL.Null,
		Common: CommonError
	});
	const UpdateAssetPriceResult = IDL.Variant({
		Ok: IDL.Null,
		Err: UpdateAssetPriceError
	});
	const UpdateCollateralAllowedDomainsParams = IDL.Record({
		allowed_balance_domains: IDL.Vec(BalanceDomain),
		asset_id: IDL.Text
	});
	const UpdateCollateralAllowedDomainsError = IDL.Variant({
		AssetNotFound: IDL.Null,
		InvalidAllowedBalanceDomains: IDL.Null
	});
	const UpdateCollateralAllowedDomainsResult = IDL.Variant({
		Ok: IDL.Null,
		Err: UpdateCollateralAllowedDomainsError
	});
	const UpdateCollateralAssetParams = IDL.Record({
		config: CollateralAssetConfig
	});
	const UpdateDomainPolicyParams = IDL.Record({
		domain: BalanceDomain,
		policy: DomainPolicy
	});
	const WithdrawCollateralParams = IDL.Record({
		domain: IDL.Opt(BalanceDomain),
		withdrawal_id: IDL.Text,
		asset_id: IDL.Text,
		amount: IDL.Nat
	});
	const WithdrawCollateralError = IDL.Variant({
		InsufficientExcessMargin: IDL.Record({
			requested: IDL.Nat,
			available: IDL.Nat
		}),
		DomainNotAllowed: IDL.Record({
			domain: BalanceDomain,
			asset_id: IDL.Text
		}),
		MathOverflow: IDL.Null,
		Asset: AssetError
	});
	const WithdrawCollateralResult = IDL.Variant({
		Ok: IDL.Null,
		Err: WithdrawCollateralError
	});
	const FundType = IDL.Variant({
		Insurance: IDL.Null,
		Treasury: IDL.Null
	});
	const WithdrawFundParams = IDL.Record({
		to: IDL.Principal,
		request_id: IDL.Text,
		fund_type: FundType,
		asset_id: IDL.Text,
		amount: IDL.Nat
	});
	const WithdrawFundError = IDL.Variant({
		TransferFailed: IDL.Text,
		InsufficientFunds: IDL.Null,
		Common: CommonError
	});
	const WithdrawFundResult = IDL.Variant({
		Ok: IDL.Nat,
		Err: WithdrawFundError
	});

	return IDL.Service({
		accept_position_transfer: IDL.Func([PositionProof], [AcceptPositionTransferResult], []),
		aggregate_lean: IDL.Func([AggregateLeanParams], [AggregateLean], ['query']),
		aggregate_settlement_accuracy: IDL.Func(
			[AggregateSettlementAccuracyParams],
			[IDL.Vec(SettlementAccuracyEntry)],
			['query']
		),
		backfill_settlement_events: IDL.Func(
			[BackfillSettlementEventsParams],
			[BackfillSettlementEventsResult],
			[]
		),
		cancel_fund_withdrawal: IDL.Func(
			[CancelFundWithdrawalParams],
			[CancelFundWithdrawalResult],
			[]
		),
		cancel_limit_order: IDL.Func([CancelLimitOrderParams], [SubmitMatchedTradeResult], []),
		config: IDL.Func([], [Config], ['query']),
		deposit_collateral: IDL.Func([DepositCollateralParams], [DepositCollateralResult], []),
		freeze_position_for_transfer: IDL.Func(
			[FreezePositionForTransferParams],
			[IDL.Opt(PositionProof)],
			[]
		),
		get_account_state: IDL.Func([GetAccountStateParams], [GetAccountStateResult], []),
		get_account_state_query: IDL.Func([], [GetAccountStateResult], ['query']),
		get_domain_policies: IDL.Func([], [IDL.Vec(IDL.Tuple(BalanceDomain, DomainPolicy))], ['query']),
		get_funds: IDL.Func([], [GetFundsResult], ['query']),
		get_orders: IDL.Func([], [IDL.Vec(LimitOrder)], ['query']),
		get_position: IDL.Func([GetPositionParams], [IDL.Opt(Position)], ['query']),
		get_positions: IDL.Func([], [IDL.Vec(Position)], ['query']),
		get_registry_canister: IDL.Func([], [IDL.Principal], ['query']),
		get_series_price_history: IDL.Func(
			[GetSeriesPriceHistoryParams],
			[SeriesPriceHistory],
			['query']
		),
		get_settlement_plan: IDL.Func([IDL.Text], [IDL.Opt(SettlementPlan)], ['query']),
		get_settlement_status: IDL.Func([IDL.Text], [IDL.Opt(SettlementStatusView)], ['query']),
		get_trade_history: IDL.Func([], [IDL.Vec(Event)], ['query']),
		get_usd_decimals: IDL.Func([], [IDL.Nat8], ['query']),
		http_request: IDL.Func([HttpRequest], [HttpResponse], ['query']),
		list_collateral_assets: IDL.Func([], [IDL.Vec(CollateralAssetInfo)], ['query']),
		list_leaderboard: IDL.Func([ListLeaderboardParams], [LeaderboardPage], ['query']),
		list_orders: IDL.Func([ListOrdersParams], [IDL.Vec(LimitOrder)], ['query']),
		list_series: IDL.Func([], [IDL.Vec(Series)], ['query']),
		list_series_settlement_statuses: IDL.Func(
			[ListSeriesSettlementStatusesParams],
			[IDL.Vec(SeriesSettlementStatus)],
			['query']
		),
		list_series_trade_history: IDL.Func(
			[ListSeriesTradeHistoryParams],
			[SeriesTradeHistoryPage],
			['query']
		),
		list_series_traded_volumes: IDL.Func(
			[ListSeriesTradedVolumesParams],
			[IDL.Vec(SeriesTradedVolume)],
			['query']
		),
		list_settled_series: IDL.Func([ListSettledSeriesParams], [SettledSeriesPage], ['query']),
		metrics: IDL.Func([], [IDL.Text], ['query']),
		migrate_domain: IDL.Func([MigrateDomainParams], [MigrateDomainResult], []),
		mint_complete_set: IDL.Func([IDL.Text, IDL.Int], [SubmitMatchedTradeResult], []),
		redeem_complete_set: IDL.Func([IDL.Text, IDL.Int], [SubmitMatchedTradeResult], []),
		refresh_icrc_asset_metadata: IDL.Func(
			[RefreshIcrcAssetMetadataParams],
			[RefreshIcrcAssetMetadataResult],
			[]
		),
		register_icrc_asset: IDL.Func([RegisterIcrcAssetParams], [RegisterIcrcAssetResult], []),
		resume_settlement: IDL.Func([IDL.Text], [SettleSeriesResult], []),
		set_registry_canister: IDL.Func([IDL.Principal], [], []),
		settle_series: IDL.Func([SettleSeriesParams], [SettleSeriesResult], []),
		stats: IDL.Func([], [Stats], ['query']),
		submit_limit_order: IDL.Func([SubmitLimitOrderParams], [SubmitMatchedTradeResult], []),
		submit_market_order: IDL.Func([SubmitMarketOrderParams], [SubmitMatchedTradeResult], []),
		submit_matched_trade: IDL.Func([SubmitMatchedTradeParams], [SubmitMatchedTradeResult], []),
		update_asset_metrics: IDL.Func([UpdateAssetMetricsParams], [], []),
		update_asset_price: IDL.Func([UpdateAssetPriceParams], [UpdateAssetPriceResult], []),
		update_collateral_allowed_domains: IDL.Func(
			[UpdateCollateralAllowedDomainsParams],
			[UpdateCollateralAllowedDomainsResult],
			[]
		),
		update_collateral_asset: IDL.Func([UpdateCollateralAssetParams], [], []),
		update_config: IDL.Func([Config], [], []),
		update_domain_policy: IDL.Func([UpdateDomainPolicyParams], [], []),
		withdraw_collateral: IDL.Func([WithdrawCollateralParams], [WithdrawCollateralResult], []),
		withdraw_fund: IDL.Func([WithdrawFundParams], [WithdrawFundResult], [])
	});
};

export const init = ({ IDL }) => {
	const ErcToken = IDL.Record({
		decimals: IDL.Nat8,
		token_address: IDL.Text,
		chain_id: IDL.Nat64
	});
	const NativeEvmAsset = IDL.Record({
		decimals: IDL.Nat8,
		chain_id: IDL.Nat64
	});
	const Asset = IDL.Variant({
		Erc20: ErcToken,
		Icrc: IDL.Principal,
		NativeEvm: NativeEvmAsset
	});
	const BalanceDomain = IDL.Variant({
		ViciXp: IDL.Null,
		Social: IDL.Null,
		Playground: IDL.Null,
		Settlement: IDL.Null
	});
	const CollateralAssetConfig = IDL.Record({
		decimals: IDL.Nat8,
		asset: Asset,
		is_enabled: IDL.Bool,
		allowed_balance_domains: IDL.Vec(BalanceDomain),
		oracle_id: IDL.Opt(IDL.Text),
		asset_id: IDL.Text,
		symbol: IDL.Text
	});
	const Config = IDL.Record({
		insurance_fund_fee_ratio: IDL.Nat16,
		internal_ledger: CollateralAssetConfig,
		signer_canister: IDL.Principal,
		version: IDL.Nat32,
		evm_rpc: IDL.Principal,
		protocol_fee_ratio: IDL.Nat16
	});

	return [Config];
};
